export const DRUGS = {
  // SSRIs
  lexapro: {
    name: 'Lexapro',
    generic: 'escitalopram',
    class: 'SSRI',
    slug: 'lexapro',
    halfLife: '27–32 hours',
    commonDoses: '5mg, 10mg, 20mg',
    taperNotes: 'Hyperbolic taper recommended. Liquid formulation (1mg/mL) available for precise final cuts below 5mg.',
    withdrawalSymptoms: ['brain zaps', 'dizziness', 'insomnia', 'irritability', 'nausea', 'emotional blunting'],
    maudsleyGuidance: 'Reduce by proportionally smaller amounts at lower doses. Final reductions (2.5mg → 0) are often the hardest. Consider liquid formulation for cuts below 2.5mg.',
    color: '#3b82f6',
    description: 'Escitalopram is the therapeutically active S-enantiomer of citalopram, an SSRI used for the treatment of major depressive disorder and generalized anxiety disorder. It is considered one of the most selective SSRIs available.',
    mechanismOfAction: 'Selective serotonin reuptake inhibitor (SSRI) that binds with high affinity to the serotonin transporter (SERT), blocking reuptake of serotonin into the presynaptic neuron and increasing serotonergic neurotransmission.',
    absorption: 'Rapidly absorbed after oral administration, Tmax ~5 hours, bioavailability ~80%, unaffected by food.',
    volumeOfDistribution: '~12 L/kg',
    proteinBinding: '~56%',
    metabolism: 'Hepatic via CYP3A4 and CYP2C19 to S-demethylcitalopram (S-DCT) and S-didemethylcitalopram (S-DDCT), both with minimal pharmacological activity.',
    routeOfElimination: 'Renal (~8% excreted unchanged) and hepatic metabolism.',
    clearance: '~600 mL/min (oral clearance)',
    toxicity: 'Serotonin syndrome at high doses or in combination with serotonergic agents. QT prolongation rare but dose-dependent.',
    foodInteractions: [
      'Grapefruit juice may increase levels via CYP3A4 inhibition',
      'No significant food effect on absorption',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (risk of serotonin syndrome)',
      'CYP2C19 inhibitors (e.g., omeprazole) may increase escitalopram levels',
      'Serotonergic drugs (triptans, tramadol, St. John\'s Wort) increase serotonin syndrome risk',
      'NSAIDs and anticoagulants increase bleeding risk',
      'Pimozide — contraindicated (QT prolongation)',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Pimozide',
      'Known hypersensitivity to escitalopram or citalopram',
    ],
    availableFormulations: [
      'Tablets: 5mg, 10mg, 20mg',
      'Oral solution: 1mg/mL',
    ],
    fdaApprovalYear: 2002,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },
  zoloft: {
    name: 'Zoloft',
    generic: 'sertraline',
    class: 'SSRI',
    slug: 'zoloft',
    halfLife: '26 hours',
    commonDoses: '25mg, 50mg, 100mg, 200mg',
    taperNotes: 'Liquid formulation available for precise dosing. Hyperbolic taper recommended.',
    withdrawalSymptoms: ['brain zaps', 'dizziness', 'irritability', 'insomnia', 'GI upset'],
    maudsleyGuidance: 'Follow hyperbolic reduction schedule. Liquid concentrate (20mg/mL) useful for fine adjustments.',
    color: '#06b6d4',
    description: 'Sertraline is an SSRI antidepressant approved for major depressive disorder, OCD, panic disorder, PTSD, social anxiety disorder, and premenstrual dysphoric disorder. It is one of the most widely prescribed antidepressants worldwide.',
    mechanismOfAction: 'Potent and selective inhibitor of serotonin reuptake at the presynaptic membrane (SERT), with minimal effects on norepinephrine and dopamine reuptake. Also has mild affinity for the dopamine transporter.',
    absorption: 'Slowly absorbed after oral administration, Tmax 4.5–8.4 hours. Bioavailability subject to extensive first-pass metabolism. Food increases Tmax slightly.',
    volumeOfDistribution: '~20 L/kg',
    proteinBinding: '~98%',
    metabolism: 'Extensive hepatic metabolism primarily via CYP2B6, CYP2C9, CYP2C19, CYP2D6, and CYP3A4 to N-desmethylsertraline (substantially less active).',
    routeOfElimination: 'Renal (~40–45% as metabolites) and fecal (~40–45%). Less than 0.2% excreted unchanged in urine.',
    clearance: '~1.5 L/min (oral clearance)',
    toxicity: 'Serotonin syndrome in overdose or with serotonergic combinations. QT prolongation reported rarely. GI bleeding risk increased with NSAIDs.',
    foodInteractions: [
      'Food increases peak plasma levels by ~25%',
      'Oral concentrate must be diluted before use; avoid mixing with grapefruit juice',
      'Avoid alcohol during treatment',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (serotonin syndrome risk)',
      'Pimozide — contraindicated',
      'Disulfiram — oral concentrate contains alcohol',
      'Serotonergic drugs (triptans, tramadol, St. John\'s Wort) increase risk of serotonin syndrome',
      'CYP2D6 substrates may have increased levels',
      'NSAIDs and anticoagulants increase bleeding risk',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Pimozide',
      'Disulfiram (oral concentrate contains alcohol)',
      'Known hypersensitivity to sertraline',
    ],
    availableFormulations: [
      'Tablets: 25mg, 50mg, 100mg',
      'Oral concentrate: 20mg/mL',
    ],
    fdaApprovalYear: 1991,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },
  paxil: {
    name: 'Paxil',
    generic: 'paroxetine',
    class: 'SSRI',
    slug: 'paxil',
    halfLife: '21 hours',
    commonDoses: '10mg, 20mg, 30mg, 40mg',
    taperNotes: 'Short half-life for an SSRI. Liquid formulation available. Often considered one of the harder SSRIs to taper.',
    withdrawalSymptoms: ['brain zaps', 'dizziness', 'electric shocks', 'crying spells', 'flu-like symptoms'],
    maudsleyGuidance: 'Particularly difficult to stop due to short half-life and anticholinergic withdrawal. Very slow final taper essential.',
    color: '#f97316',
    description: 'Paroxetine is an SSRI with notable anticholinergic activity, approved for major depressive disorder, OCD, panic disorder, social anxiety disorder, GAD, and PTSD. It is widely recognized as one of the more difficult SSRIs to discontinue.',
    mechanismOfAction: 'Potent and selective inhibitor of serotonin reuptake (SERT). Also has significant anticholinergic (muscarinic) activity and weak norepinephrine reuptake inhibition, which contribute to its withdrawal profile.',
    absorption: 'Completely absorbed after oral dosing but extensive first-pass metabolism reduces bioavailability to ~50%. Tmax ~5 hours. Food does not significantly affect absorption.',
    volumeOfDistribution: '~8.7 L/kg',
    proteinBinding: '~93–95%',
    metabolism: 'Extensively metabolized hepatically via CYP2D6 (primary) with CYP3A4 contribution. Paroxetine inhibits its own metabolism (CYP2D6 saturation), leading to non-linear pharmacokinetics.',
    routeOfElimination: 'Renal (~64% as metabolites, ~2% unchanged) and fecal (~36%).',
    clearance: 'Non-linear; clearance decreases at higher doses due to CYP2D6 saturation.',
    toxicity: 'Serotonin syndrome risk. Anticholinergic toxicity at high doses. Associated with higher rates of discontinuation syndrome than other SSRIs.',
    foodInteractions: [
      'No significant food effect on absorption',
      'Avoid alcohol during treatment',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (serotonin syndrome risk)',
      'Thioridazine — contraindicated (QT prolongation via CYP2D6 inhibition)',
      'Pimozide — contraindicated',
      'Strong CYP2D6 inhibitor; increases levels of tamoxifen (reduces efficacy), codeine (reduces activation)',
      'Serotonergic drugs increase serotonin syndrome risk',
      'NSAIDs and anticoagulants increase bleeding risk',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Thioridazine',
      'Pimozide',
      'Known hypersensitivity to paroxetine',
    ],
    availableFormulations: [
      'Tablets: 10mg, 20mg, 30mg, 40mg',
      'Oral suspension: 10mg/5mL',
      'Controlled-release (CR) tablets: 12.5mg, 25mg, 37.5mg',
    ],
    fdaApprovalYear: 1992,
    pregnancyCategory: 'Category D (positive evidence of risk — cardiac malformations)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },
  prozac: {
    name: 'Prozac',
    generic: 'fluoxetine',
    class: 'SSRI',
    slug: 'prozac',
    halfLife: '4–6 days (norfluoxetine 4–16 days)',
    commonDoses: '10mg, 20mg, 40mg, 60mg',
    taperNotes: 'Very long half-life makes it the easiest SSRI to taper. Sometimes used as a bridge for tapering other SSRIs/SNRIs.',
    withdrawalSymptoms: ['dizziness', 'irritability', 'insomnia', 'nausea'],
    maudsleyGuidance: 'Long half-life provides built-in buffering. Still recommended to taper gradually rather than abrupt stop.',
    color: '#22c55e',
    description: 'Fluoxetine was the first SSRI approved in the US and remains one of the most widely prescribed antidepressants. It is approved for major depressive disorder, OCD, panic disorder, bulimia nervosa, and bipolar depression (in combination with olanzapine).',
    mechanismOfAction: 'Selective serotonin reuptake inhibitor (SSRI) that blocks the serotonin transporter (SERT). Its active metabolite norfluoxetine is also a potent SSRI, contributing to an extremely long effective half-life.',
    absorption: 'Well absorbed after oral administration. Bioavailability ~72%. Tmax 6–8 hours. Food slightly delays absorption but does not affect overall extent.',
    volumeOfDistribution: '~20–45 L/kg',
    proteinBinding: '~94.5%',
    metabolism: 'Hepatic via CYP2D6 (primary) and CYP2C9 to the active metabolite norfluoxetine. Fluoxetine is a potent CYP2D6 inhibitor.',
    routeOfElimination: 'Renal (~80%, with ~2.5% as unchanged fluoxetine and ~10% as norfluoxetine). Fecal (~15%).',
    clearance: 'Apparent oral clearance ~600 mL/min; decreases with chronic dosing due to CYP2D6 inhibition.',
    toxicity: 'Serotonin syndrome at supratherapeutic doses. QT prolongation rarely reported. Lower toxicity in overdose compared to TCAs.',
    foodInteractions: [
      'No significant food effect on absorption',
      'Grapefruit juice may modestly increase levels',
      'Avoid alcohol during treatment',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (allow 5 weeks washout due to long half-life)',
      'Thioridazine — contraindicated (QT prolongation)',
      'Pimozide — contraindicated',
      'Potent CYP2D6 inhibitor; affects metabolism of tamoxifen, codeine, TCAs, and many antipsychotics',
      'Serotonergic drugs increase serotonin syndrome risk',
      'NSAIDs and anticoagulants increase bleeding risk',
    ],
    contraindications: [
      'MAOIs within 14 days (5 weeks washout before starting MAOI)',
      'Thioridazine',
      'Pimozide',
      'Known hypersensitivity to fluoxetine',
    ],
    availableFormulations: [
      'Capsules: 10mg, 20mg, 40mg',
      'Tablets: 10mg, 20mg, 60mg',
      'Oral solution: 20mg/5mL',
      'Delayed-release capsules (weekly): 90mg',
    ],
    fdaApprovalYear: 1987,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },
  celexa: {
    name: 'Celexa',
    generic: 'citalopram',
    class: 'SSRI',
    slug: 'celexa',
    halfLife: '35 hours',
    commonDoses: '10mg, 20mg, 40mg',
    taperNotes: 'Liquid formulation available. Hyperbolic taper recommended for final reductions.',
    withdrawalSymptoms: ['brain zaps', 'dizziness', 'nausea', 'irritability', 'insomnia'],
    maudsleyGuidance: 'Oral solution (10mg/5mL) available for precise dose reductions. Follow hyperbolic tapering schedule.',
    color: '#6366f1',
    description: 'Citalopram is a racemic SSRI approved for major depressive disorder. It is the racemic form of escitalopram and one of the most selective SSRIs for the serotonin transporter. The FDA limits maximum dose to 40mg due to dose-dependent QT prolongation.',
    mechanismOfAction: 'Selective serotonin reuptake inhibitor (SSRI) that blocks the serotonin transporter (SERT) with high selectivity. The S-enantiomer is responsible for most of the therapeutic activity.',
    absorption: 'Rapidly and well absorbed after oral administration. Bioavailability ~80%. Tmax ~4 hours. Food does not significantly affect absorption.',
    volumeOfDistribution: '~12 L/kg',
    proteinBinding: '~80%',
    metabolism: 'Hepatic via CYP3A4 and CYP2C19 (primary) to demethylcitalopram (DCT) and didemethylcitalopram (DDCT), both with weak pharmacological activity.',
    routeOfElimination: 'Renal (~10% unchanged) and hepatic metabolism. Fecal excretion minor.',
    clearance: '~330 mL/min (oral clearance)',
    toxicity: 'Dose-dependent QT prolongation (maximum recommended dose 40mg/day, 20mg/day in patients >60 years). Serotonin syndrome with serotonergic combinations.',
    foodInteractions: [
      'No significant food effect on absorption',
      'Avoid alcohol during treatment',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (serotonin syndrome risk)',
      'Pimozide — contraindicated (QT prolongation)',
      'QT-prolonging drugs should be used cautiously',
      'CYP2C19 inhibitors (e.g., omeprazole, esomeprazole) increase citalopram levels — max dose 20mg/day with CYP2C19 inhibitors',
      'Serotonergic drugs increase serotonin syndrome risk',
      'NSAIDs and anticoagulants increase bleeding risk',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Pimozide',
      'Congenital long QT syndrome',
      'Known hypersensitivity to citalopram',
    ],
    availableFormulations: [
      'Tablets: 10mg, 20mg, 40mg',
      'Oral solution: 10mg/5mL',
    ],
    fdaApprovalYear: 1998,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },
  trintellix: {
    name: 'Trintellix',
    generic: 'vortioxetine',
    class: 'SSRI',
    slug: 'trintellix',
    halfLife: '66 hours',
    commonDoses: '5mg, 10mg, 20mg',
    taperNotes: 'Relatively long half-life. Tablets can be split. Limited withdrawal data compared to older SSRIs.',
    withdrawalSymptoms: ['dizziness', 'nausea', 'headache', 'irritability'],
    maudsleyGuidance: 'Newer drug with less tapering data. Apply general SSRI hyperbolic tapering principles. Tablets may be split.',
    color: '#0ea5e9',
    description: 'Vortioxetine is a multimodal serotonergic antidepressant approved for major depressive disorder. Beyond SERT inhibition, it has direct activity at multiple serotonin receptors, which may contribute to pro-cognitive effects.',
    mechanismOfAction: 'Multimodal serotonergic agent: inhibits the serotonin transporter (SERT) and also acts as a 5-HT3, 5-HT7, and 5-HT1D receptor antagonist, 5-HT1B partial agonist, and 5-HT1A agonist.',
    absorption: 'Well absorbed orally. Absolute bioavailability ~75%. Tmax 7–11 hours. Food does not affect pharmacokinetics.',
    volumeOfDistribution: '~2600 L (~33 L/kg)',
    proteinBinding: '~98%',
    metabolism: 'Extensively metabolized hepatically via CYP2D6 (primary), CYP3A4/5, CYP2C9, CYP2C19, CYP2A6, and CYP2C8. Major metabolite is pharmacologically inactive.',
    routeOfElimination: 'Renal (~59%) and fecal (~26%). Negligible unchanged drug in urine.',
    clearance: '~33 L/hr (oral clearance)',
    toxicity: 'Serotonin syndrome with serotonergic combinations. Generally well tolerated; nausea is the most common adverse effect.',
    foodInteractions: [
      'No significant food effect on pharmacokinetics',
      'Avoid alcohol during treatment',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (serotonin syndrome risk)',
      'Strong CYP2D6 inhibitors (e.g., bupropion, fluoxetine, paroxetine) increase vortioxetine levels — reduce dose by 50%',
      'Strong CYP inducers (e.g., rifampin, carbamazepine) decrease vortioxetine levels — consider dose increase',
      'Serotonergic drugs increase serotonin syndrome risk',
      'NSAIDs and anticoagulants increase bleeding risk',
    ],
    contraindications: [
      'MAOIs within 21 days',
      'Known hypersensitivity to vortioxetine',
    ],
    availableFormulations: [
      'Tablets: 5mg, 10mg, 20mg',
    ],
    fdaApprovalYear: 2013,
    pregnancyCategory: 'No assigned category; see FDA labeling (approved post-2015 PLLR rule)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },
  luvox: {
    name: 'Luvox',
    generic: 'fluvoxamine',
    class: 'SSRI',
    slug: 'luvox',
    halfLife: '15–22 hours',
    commonDoses: '25mg, 50mg, 100mg, 200mg',
    taperNotes: 'Short half-life. CR formulation available. Tablets can be split for gradual reduction.',
    withdrawalSymptoms: ['brain zaps', 'dizziness', 'nausea', 'insomnia', 'irritability'],
    maudsleyGuidance: 'Shorter half-life than most SSRIs; slower taper pace recommended. Tablets can be dissolved in water for precise dosing.',
    color: '#8b5cf6',
    description: 'Fluvoxamine is an SSRI primarily approved for obsessive-compulsive disorder (OCD). It is a potent inhibitor of CYP1A2 and CYP2C19 and also has sigma-1 receptor agonist activity, which may contribute to its anxiolytic properties.',
    mechanismOfAction: 'Selective serotonin reuptake inhibitor (SSRI) that potently inhibits the serotonin transporter (SERT). Also acts as a sigma-1 receptor agonist, which may provide additional anti-anxiety and neuroprotective effects.',
    absorption: 'Completely absorbed after oral administration. Bioavailability ~53% due to first-pass metabolism. Tmax 3–8 hours. Food does not significantly affect absorption.',
    volumeOfDistribution: '~25 L/kg',
    proteinBinding: '~77–80%',
    metabolism: 'Extensively metabolized hepatically via CYP2D6 and CYP1A2. Potent inhibitor of CYP1A2 and CYP2C19, moderate inhibitor of CYP2C9 and CYP3A4. No active metabolites.',
    routeOfElimination: 'Renal (~94% as metabolites, ~2% unchanged).',
    clearance: '~1400 mL/min (apparent oral clearance)',
    toxicity: 'Serotonin syndrome with serotonergic combinations. Significant drug interactions due to CYP1A2 inhibition (e.g., with theophylline, clozapine, tizanidine).',
    foodInteractions: [
      'No significant food effect on absorption',
      'Caffeine levels may increase significantly due to CYP1A2 inhibition',
      'Avoid alcohol during treatment',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (serotonin syndrome risk)',
      'Thioridazine — contraindicated',
      'Alosetron — contraindicated (CYP1A2 inhibition)',
      'Tizanidine — contraindicated (CYP1A2 inhibition greatly increases tizanidine levels)',
      'Pimozide — contraindicated',
      'Potent CYP1A2 inhibitor: increases theophylline, clozapine, caffeine, warfarin levels',
      'Serotonergic drugs increase serotonin syndrome risk',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Thioridazine',
      'Alosetron',
      'Tizanidine',
      'Pimozide',
      'Known hypersensitivity to fluvoxamine',
    ],
    availableFormulations: [
      'Tablets: 25mg, 50mg, 100mg',
      'Extended-release capsules (CR): 100mg, 150mg',
    ],
    fdaApprovalYear: 1994,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },

  // SNRIs
  effexor: {
    name: 'Effexor',
    generic: 'venlafaxine',
    class: 'SNRI',
    slug: 'effexor',
    halfLife: '5 hours (active metabolite 11h)',
    commonDoses: '37.5mg, 75mg, 150mg, 225mg',
    taperNotes: 'Very short half-life makes this one of the hardest drugs to taper. Bead counting from capsules gives precise dose control.',
    withdrawalSymptoms: ['brain zaps', 'severe dizziness', 'nausea', 'electric shock sensations', 'crying spells', 'rage', 'depersonalization'],
    maudsleyGuidance: 'Extremely slow taper essential due to short half-life. Bead counting recommended. Some clinicians bridge with fluoxetine (longer half-life) for final discontinuation.',
    color: '#ef4444',
    description: 'Venlafaxine is an SNRI approved for major depressive disorder, generalized anxiety disorder, social anxiety disorder, and panic disorder. It is well known for having one of the most challenging discontinuation syndromes among antidepressants.',
    mechanismOfAction: 'Serotonin-norepinephrine reuptake inhibitor (SNRI). At lower doses primarily inhibits serotonin reuptake; norepinephrine reuptake inhibition becomes more prominent at doses ≥150mg. Weak dopamine reuptake inhibition at high doses.',
    absorption: 'Well absorbed orally (~92%). Extensive first-pass metabolism; bioavailability ~45%. Tmax 2 hours (IR), 5.5 hours (XR). Food slightly delays but does not affect extent of absorption.',
    volumeOfDistribution: '~7.5 L/kg',
    proteinBinding: '~27% (venlafaxine), ~30% (O-desmethylvenlafaxine)',
    metabolism: 'Hepatic primarily via CYP2D6 to the active metabolite O-desmethylvenlafaxine (desvenlafaxine). CYP3A4 contributes to N-desmethylvenlafaxine (less active).',
    routeOfElimination: 'Renal (~87%, with ~5% as unchanged venlafaxine and ~29% as desvenlafaxine). Fecal minimal.',
    clearance: '~1.3 L/hr/kg (venlafaxine), ~0.4 L/hr/kg (desvenlafaxine)',
    toxicity: 'Serotonin syndrome. Sustained hypertension at higher doses. Seizures in overdose. Discontinuation syndrome is among the most severe of all antidepressants.',
    foodInteractions: [
      'Food delays absorption but does not reduce bioavailability',
      'Avoid alcohol during treatment',
      'Grapefruit juice may modestly increase levels',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (serotonin syndrome risk)',
      'Serotonergic drugs (triptans, tramadol, St. John\'s Wort) increase serotonin syndrome risk',
      'CYP2D6 inhibitors may increase venlafaxine levels (but reduce active metabolite formation)',
      'CYP3A4 inhibitors may increase venlafaxine levels',
      'NSAIDs and anticoagulants increase bleeding risk',
      'May increase levels of drugs metabolized by CYP2D6',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Known hypersensitivity to venlafaxine or desvenlafaxine',
    ],
    availableFormulations: [
      'Extended-release capsules (XR): 37.5mg, 75mg, 150mg',
      'Immediate-release tablets: 25mg, 37.5mg, 50mg, 75mg, 100mg',
    ],
    fdaApprovalYear: 1993,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },
  cymbalta: {
    name: 'Cymbalta',
    generic: 'duloxetine',
    class: 'SNRI',
    slug: 'cymbalta',
    halfLife: '12 hours',
    commonDoses: '20mg, 30mg, 60mg, 120mg',
    taperNotes: 'Capsules contain enteric-coated pellets. Bead counting possible but pellets are very small.',
    withdrawalSymptoms: ['brain zaps', 'nausea', 'dizziness', 'headache', 'irritability', 'insomnia'],
    maudsleyGuidance: 'Bead counting from capsules for gradual reduction. Some pharmacies can compound liquid formulation.',
    color: '#ec4899',
    description: 'Duloxetine is an SNRI approved for major depressive disorder, generalized anxiety disorder, diabetic peripheral neuropathic pain, fibromyalgia, and chronic musculoskeletal pain. It is known for a difficult discontinuation syndrome.',
    mechanismOfAction: 'Potent inhibitor of both serotonin and norepinephrine reuptake (SNRI). Unlike venlafaxine, it inhibits both transporters at standard therapeutic doses. Weak inhibitor of dopamine reuptake.',
    absorption: 'Well absorbed, but enteric coating delays absorption (Tmax 6 hours). Bioavailability ~50% (range 32–80%). Food delays Tmax by 6–10 hours and reduces AUC slightly.',
    volumeOfDistribution: '~1640 L (~23 L/kg)',
    proteinBinding: '>90% (primarily albumin and alpha-1-acid glycoprotein)',
    metabolism: 'Extensively metabolized hepatically via CYP1A2 (primary) and CYP2D6. Numerous metabolites, none pharmacologically active.',
    routeOfElimination: 'Renal (~70% as metabolites, <1% unchanged) and fecal (~20%).',
    clearance: '~114 L/hr (apparent oral clearance)',
    toxicity: 'Serotonin syndrome with serotonergic combinations. Hepatotoxicity rare but reported. Severe discontinuation syndrome. Avoid in hepatic impairment and heavy alcohol use.',
    foodInteractions: [
      'Food delays absorption but does not significantly change total exposure',
      'Avoid heavy alcohol use (hepatotoxicity risk)',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (serotonin syndrome risk)',
      'CYP1A2 inhibitors (e.g., fluvoxamine, ciprofloxacin) substantially increase duloxetine levels — avoid combination',
      'CYP2D6 inhibitors increase duloxetine levels',
      'Potent inhibitor of CYP2D6; increases levels of metoprolol, desipramine, and other CYP2D6 substrates',
      'Serotonergic drugs increase serotonin syndrome risk',
      'NSAIDs and anticoagulants increase bleeding risk',
      'Thioridazine — avoid (QT prolongation)',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Uncontrolled narrow-angle glaucoma',
      'Severe hepatic impairment',
      'Concomitant use with potent CYP1A2 inhibitors (e.g., fluvoxamine)',
      'Known hypersensitivity to duloxetine',
    ],
    availableFormulations: [
      'Delayed-release capsules: 20mg, 30mg, 60mg',
    ],
    fdaApprovalYear: 2004,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },
  pristiq: {
    name: 'Pristiq',
    generic: 'desvenlafaxine',
    class: 'SNRI',
    slug: 'pristiq',
    halfLife: '11 hours',
    commonDoses: '25mg, 50mg, 100mg',
    taperNotes: 'Extended-release tablets cannot be split. Compounding pharmacy needed for doses between available strengths.',
    withdrawalSymptoms: ['brain zaps', 'dizziness', 'nausea', 'irritability', 'headache'],
    maudsleyGuidance: 'Tablets cannot be crushed/split. Compounding pharmacy essential for fine reductions.',
    color: '#f43f5e',
    description: 'Desvenlafaxine is the active metabolite of venlafaxine, formulated as an extended-release SNRI for major depressive disorder. It was designed to provide more predictable pharmacokinetics by bypassing CYP2D6 metabolism.',
    mechanismOfAction: 'Serotonin-norepinephrine reuptake inhibitor (SNRI). Inhibits both the serotonin and norepinephrine transporters. Unlike its parent compound venlafaxine, it does not require CYP2D6 activation.',
    absorption: 'Bioavailability ~80%. Tmax ~7.5 hours. Food does not significantly affect pharmacokinetics.',
    volumeOfDistribution: '~3.4 L/kg',
    proteinBinding: '~30%',
    metabolism: 'Hepatic conjugation (UGT) and to a minor extent CYP3A4-mediated oxidation. Does not rely on CYP2D6 for activation.',
    routeOfElimination: 'Renal (~45% unchanged, ~24% as glucuronide conjugate). Total urinary recovery ~~70%.',
    clearance: '~215 mL/min (total body clearance)',
    toxicity: 'Serotonin syndrome with serotonergic combinations. Sustained hypertension. Lipid elevations reported. Severe discontinuation syndrome similar to venlafaxine.',
    foodInteractions: [
      'No significant food effect on pharmacokinetics',
      'Avoid alcohol during treatment',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (serotonin syndrome risk)',
      'Serotonergic drugs increase serotonin syndrome risk',
      'Weak inhibitor of CYP2D6; minor effect on CYP2D6 substrates',
      'NSAIDs and anticoagulants increase bleeding risk',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Known hypersensitivity to desvenlafaxine or venlafaxine',
    ],
    availableFormulations: [
      'Extended-release tablets: 25mg, 50mg, 100mg',
    ],
    fdaApprovalYear: 2008,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },

  // TCAs
  amitriptyline: {
    name: 'Amitriptyline',
    generic: 'amitriptyline',
    class: 'TCA',
    slug: 'amitriptyline',
    halfLife: '10–50 hours',
    commonDoses: '10mg, 25mg, 50mg, 75mg, 100mg',
    taperNotes: 'Available in multiple tablet strengths and liquid formulation. Anticholinergic rebound common during withdrawal.',
    withdrawalSymptoms: ['insomnia', 'nausea', 'headache', 'GI upset', 'anxiety', 'muscle aches'],
    maudsleyGuidance: 'Multiple available strengths (10, 25, 50, 75mg) allow stepwise reduction. Liquid formulation available for fine adjustments.',
    color: '#d946ef',
    description: 'Amitriptyline is a tertiary amine tricyclic antidepressant (TCA) used for major depressive disorder. It is also widely used off-label for chronic pain, migraine prophylaxis, and insomnia. It has strong anticholinergic, antihistaminic, and alpha-adrenergic blocking properties.',
    mechanismOfAction: 'Inhibits reuptake of both serotonin and norepinephrine. Also has significant antagonist activity at histamine H1, muscarinic acetylcholine, and alpha-1 adrenergic receptors, contributing to its sedative, anticholinergic, and hypotensive effects.',
    absorption: 'Rapidly absorbed after oral administration. Extensive first-pass metabolism; bioavailability ~30–60%. Tmax 2–5 hours.',
    volumeOfDistribution: '~6–10 L/kg',
    proteinBinding: '~96%',
    metabolism: 'Hepatic via CYP2D6, CYP2C19, CYP1A2, and CYP3A4 to the active metabolite nortriptyline (via demethylation) and hydroxylated metabolites.',
    routeOfElimination: 'Renal (primarily as metabolites). Enterohepatic recirculation contributes to variable half-life.',
    clearance: '~46 L/hr (oral clearance, highly variable)',
    toxicity: 'Cardiotoxic in overdose (QRS widening, arrhythmias, cardiac arrest). Anticholinergic toxicity (urinary retention, delirium). Seizures. Low therapeutic index.',
    foodInteractions: [
      'Food does not significantly affect absorption',
      'Grapefruit juice may increase levels via CYP3A4 inhibition',
      'Avoid alcohol (additive CNS depression)',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (hypertensive crisis and serotonin syndrome)',
      'CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) significantly increase amitriptyline/nortriptyline levels',
      'QT-prolonging drugs increase risk of arrhythmia',
      'CNS depressants (opioids, benzodiazepines, alcohol) — additive sedation',
      'Anticholinergic drugs — additive anticholinergic toxicity',
      'Cimetidine increases TCA levels',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Acute recovery period post-myocardial infarction',
      'Known hypersensitivity to amitriptyline',
    ],
    availableFormulations: [
      'Tablets: 10mg, 25mg, 50mg, 75mg, 100mg, 150mg',
    ],
    fdaApprovalYear: 1961,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },
  clomipramine: {
    name: 'Clomipramine',
    generic: 'clomipramine',
    class: 'TCA',
    slug: 'clomipramine',
    halfLife: '19–37 hours',
    commonDoses: '25mg, 50mg, 75mg, 100mg',
    taperNotes: 'Strong serotonergic TCA. Withdrawal can be severe. Capsules can be opened for bead counting.',
    withdrawalSymptoms: ['brain zaps', 'nausea', 'insomnia', 'anxiety', 'dizziness', 'electric shocks'],
    maudsleyGuidance: 'Due to strong serotonin reuptake inhibition, withdrawal can resemble SSRI discontinuation. Slow hyperbolic taper recommended.',
    color: '#c026d3',
    description: 'Clomipramine is a tricyclic antidepressant with the strongest serotonin reuptake inhibition of all TCAs. It is the only TCA FDA-approved for obsessive-compulsive disorder (OCD) and is considered a gold-standard treatment for severe OCD.',
    mechanismOfAction: 'Potent inhibitor of serotonin reuptake (most serotonergic TCA) and moderate inhibitor of norepinephrine reuptake. Its metabolite desmethylclomipramine is a potent norepinephrine reuptake inhibitor. Also has anticholinergic, antihistaminic, and alpha-adrenergic blocking activity.',
    absorption: 'Well absorbed after oral administration. Extensive first-pass metabolism; bioavailability ~50%. Tmax 2–6 hours. Food does not significantly affect absorption.',
    volumeOfDistribution: '~17 L/kg',
    proteinBinding: '~97–98%',
    metabolism: 'Hepatic via CYP2D6, CYP1A2, CYP2C19, and CYP3A4 to the active metabolite desmethylclomipramine and hydroxylated metabolites.',
    routeOfElimination: 'Renal (~51–60% as metabolites) and fecal (~24–32%). Less than 1% excreted unchanged in urine.',
    clearance: 'Apparent oral clearance variable; auto-inhibition of CYP2D6 with chronic dosing.',
    toxicity: 'Cardiotoxic in overdose (QRS widening, arrhythmias). Seizures (dose-dependent, especially >250mg/day). Serotonin syndrome risk. Anticholinergic toxicity.',
    foodInteractions: [
      'Food does not significantly affect absorption',
      'Grapefruit juice may increase levels',
      'Avoid alcohol (additive CNS depression)',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (serotonin syndrome and hypertensive crisis)',
      'CYP2D6 inhibitors significantly increase clomipramine levels',
      'CYP1A2 inhibitors (fluvoxamine, ciprofloxacin) increase levels — fluvoxamine can cause dramatic elevations',
      'Serotonergic drugs increase serotonin syndrome risk',
      'QT-prolonging drugs increase arrhythmia risk',
      'CNS depressants — additive sedation',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Acute recovery period post-myocardial infarction',
      'Known hypersensitivity to clomipramine or other TCAs',
    ],
    availableFormulations: [
      'Capsules: 25mg, 50mg, 75mg',
    ],
    fdaApprovalYear: 1989,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },
  nortriptyline: {
    name: 'Nortriptyline',
    generic: 'nortriptyline',
    class: 'TCA',
    slug: 'nortriptyline',
    halfLife: '16–90 hours',
    commonDoses: '10mg, 25mg, 50mg, 75mg',
    taperNotes: 'Available in capsule and liquid forms. Less anticholinergic than amitriptyline.',
    withdrawalSymptoms: ['insomnia', 'nausea', 'anxiety', 'headache', 'irritability'],
    maudsleyGuidance: 'Oral solution (10mg/5mL) available for gradual reductions. Less sedating than amitriptyline, withdrawal may be milder.',
    color: '#a21caf',
    description: 'Nortriptyline is a secondary amine tricyclic antidepressant and the active metabolite of amitriptyline. It is used for major depressive disorder and off-label for neuropathic pain, migraine prophylaxis, and smoking cessation. It is better tolerated than amitriptyline with fewer anticholinergic and sedative effects.',
    mechanismOfAction: 'Primarily inhibits norepinephrine reuptake, with lesser serotonin reuptake inhibition. Has less anticholinergic, antihistaminic, and alpha-adrenergic blocking activity compared to tertiary amine TCAs like amitriptyline.',
    absorption: 'Well absorbed after oral administration. Bioavailability ~46–70%. Tmax 3–12 hours. Food does not significantly affect absorption.',
    volumeOfDistribution: '~21 L/kg',
    proteinBinding: '~93–95%',
    metabolism: 'Hepatic via CYP2D6 (primary) to 10-hydroxynortriptyline and other hydroxylated metabolites. Also metabolized by CYP2C19 and CYP3A4.',
    routeOfElimination: 'Renal (~40% as metabolites) with ~2% unchanged in urine. Fecal excretion minor.',
    clearance: '~500 mL/min (apparent oral clearance, highly variable depending on CYP2D6 status)',
    toxicity: 'Cardiotoxic in overdose (QRS widening, arrhythmias), though less toxic than amitriptyline. Therapeutic drug monitoring recommended (therapeutic window 50–150 ng/mL).',
    foodInteractions: [
      'Food does not significantly affect absorption',
      'Avoid alcohol (additive CNS depression)',
      'Grapefruit juice may modestly increase levels',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (hypertensive crisis and serotonin syndrome)',
      'CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) significantly increase nortriptyline levels',
      'QT-prolonging drugs increase arrhythmia risk',
      'CNS depressants — additive sedation',
      'Anticholinergic drugs — additive effects (less than amitriptyline)',
      'Cimetidine increases TCA levels',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Acute recovery period post-myocardial infarction',
      'Known hypersensitivity to nortriptyline',
    ],
    availableFormulations: [
      'Capsules: 10mg, 25mg, 50mg, 75mg',
      'Oral solution: 10mg/5mL',
    ],
    fdaApprovalYear: 1964,
    pregnancyCategory: 'Category D (positive evidence of risk)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },

  // NaSSA
  mirtazapine: {
    name: 'Mirtazapine',
    generic: 'mirtazapine',
    class: 'NaSSA',
    slug: 'mirtazapine',
    halfLife: '20–40 hours',
    commonDoses: '7.5mg, 15mg, 30mg, 45mg',
    taperNotes: 'Rebound insomnia is very common at lower doses due to stronger antihistamine effect. Paradoxically more sedating at lower doses.',
    withdrawalSymptoms: ['rebound insomnia', 'anxiety', 'nausea', 'headache', 'irritability', 'appetite changes'],
    maudsleyGuidance: 'Tablet can be split or dissolved in water for precise dosing. Rebound insomnia at lower doses often mistaken for relapse — distinguish withdrawal from relapse by timing.',
    color: '#a855f7',
    description: 'Mirtazapine is a noradrenergic and specific serotonergic antidepressant (NaSSA) approved for major depressive disorder. It has a unique mechanism that does not involve reuptake inhibition. It is known for sedation and appetite stimulation, especially at lower doses.',
    mechanismOfAction: 'Antagonist at central alpha-2 adrenergic autoreceptors and heteroreceptors, increasing noradrenergic and serotonergic neurotransmission. Also antagonizes 5-HT2A, 5-HT2C, 5-HT3, and histamine H1 receptors. The strong H1 antagonism causes sedation and weight gain.',
    absorption: 'Rapidly and completely absorbed. Bioavailability ~50%. Tmax ~2 hours. Food has minimal effect on absorption.',
    volumeOfDistribution: '~4.5 L/kg',
    proteinBinding: '~85%',
    metabolism: 'Extensively metabolized hepatically via CYP2D6, CYP3A4, and CYP1A2 to demethyl and hydroxylated metabolites, which have minimal pharmacological activity.',
    routeOfElimination: 'Renal (~75%) and fecal (~15%). Less than 5% excreted unchanged in urine.',
    clearance: '~230 mL/min (apparent oral clearance)',
    toxicity: 'Relatively low toxicity in overdose compared to TCAs. Agranulocytosis/neutropenia rarely reported. Weight gain and metabolic effects. Serotonin syndrome possible with serotonergic combinations.',
    foodInteractions: [
      'Food has minimal effect on absorption',
      'Avoid alcohol (additive CNS depression)',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (serotonin syndrome risk)',
      'Serotonergic drugs increase serotonin syndrome risk',
      'CYP3A4 inhibitors (ketoconazole) may increase mirtazapine levels',
      'CYP3A4 inducers (carbamazepine, phenytoin) may decrease mirtazapine levels',
      'CNS depressants — additive sedation',
      'Alcohol — additive cognitive and motor impairment',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Known hypersensitivity to mirtazapine',
    ],
    availableFormulations: [
      'Tablets: 7.5mg, 15mg, 30mg, 45mg',
      'Orally disintegrating tablets (SolTab): 15mg, 30mg, 45mg',
    ],
    fdaApprovalYear: 1996,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },

  // NDRI
  wellbutrin: {
    name: 'Wellbutrin',
    generic: 'bupropion',
    class: 'NDRI',
    slug: 'wellbutrin',
    halfLife: '21 hours',
    commonDoses: '75mg, 100mg, 150mg, 300mg',
    taperNotes: 'Generally easier to taper than SSRIs/SNRIs. IR tablets can be split for gradual reduction.',
    withdrawalSymptoms: ['fatigue', 'irritability', 'headache', 'insomnia', 'low mood'],
    maudsleyGuidance: 'Reduce gradually. IR formulation provides most flexibility for dose adjustments.',
    color: '#84cc16',
    description: 'Bupropion is a norepinephrine-dopamine reuptake inhibitor (NDRI) approved for major depressive disorder, seasonal affective disorder, and smoking cessation (as Zyban). It is unique among antidepressants for its activating profile and lack of sexual side effects or weight gain.',
    mechanismOfAction: 'Inhibits reuptake of norepinephrine and dopamine (NDRI). Does not significantly affect serotonin reuptake. The active metabolites hydroxybupropion, threohydrobupropion, and erythrohydrobupropion also contribute to pharmacological activity.',
    absorption: 'Well absorbed after oral administration. Tmax ~2 hours (IR), ~3 hours (SR), ~5 hours (XL). Extensive first-pass metabolism; bioavailability ~5–20%. Food does not significantly affect absorption of SR/XL formulations.',
    volumeOfDistribution: '~20 L/kg (estimated)',
    proteinBinding: '~84%',
    metabolism: 'Extensively metabolized hepatically via CYP2B6 (primary) to the active metabolite hydroxybupropion. Non-CYP pathways produce threohydrobupropion and erythrohydrobupropion.',
    routeOfElimination: 'Renal (~87%, with <1% as unchanged bupropion) and fecal (~10%).',
    clearance: '~200 L/hr (apparent oral clearance)',
    toxicity: 'Dose-dependent seizure risk (contraindicated above 450mg/day). Hypertension. Lower toxicity in overdose than TCAs but seizures and cardiac conduction delays possible.',
    foodInteractions: [
      'Food does not significantly affect SR/XL absorption',
      'Avoid alcohol (lowers seizure threshold)',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (hypertensive crisis)',
      'Potent CYP2D6 inhibitor; increases levels of TCAs, SSRIs (paroxetine, fluoxetine levels affected less), metoprolol, flecainide, and other CYP2D6 substrates',
      'CYP2B6 inhibitors (ticlopidine, clopidogrel) increase bupropion levels',
      'CYP2B6 inducers (ritonavir, lopinavir, efavirenz, carbamazepine) decrease bupropion levels',
      'Drugs that lower seizure threshold increase seizure risk',
      'Dopaminergic drugs (levodopa, amantadine) — additive CNS toxicity',
    ],
    contraindications: [
      'Seizure disorder',
      'Current or prior bulimia or anorexia nervosa (increased seizure risk)',
      'MAOIs within 14 days',
      'Abrupt discontinuation of alcohol or sedatives',
      'Known hypersensitivity to bupropion',
    ],
    availableFormulations: [
      'Immediate-release tablets: 75mg, 100mg',
      'Sustained-release tablets (SR): 100mg, 150mg, 200mg',
      'Extended-release tablets (XL): 150mg, 300mg',
    ],
    fdaApprovalYear: 1985,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },

  // Atypical Antipsychotics
  seroquel: {
    name: 'Seroquel',
    generic: 'quetiapine',
    class: 'Atypical Antipsychotic',
    slug: 'seroquel',
    halfLife: '6–7 hours',
    commonDoses: '25mg, 50mg, 100mg, 200mg, 300mg',
    taperNotes: 'Often prescribed off-label for insomnia at low doses. Rebound insomnia and anxiety common during tapering. Tablets can be split.',
    withdrawalSymptoms: ['rebound insomnia', 'nausea', 'anxiety', 'irritability', 'sweating', 'psychosis risk at high doses'],
    maudsleyGuidance: 'Reduce by no more than 10% of current dose. At low doses (25–50mg) used for sleep, very slow final taper over months.',
    color: '#f59e0b',
    description: 'Quetiapine is an atypical antipsychotic approved for schizophrenia, bipolar disorder (manic and depressive episodes), and as adjunctive treatment for major depressive disorder. It is widely prescribed off-label at low doses for insomnia and anxiety.',
    mechanismOfAction: 'Antagonist at dopamine D2, serotonin 5-HT2A, histamine H1, and alpha-1 adrenergic receptors. Its active metabolite norquetiapine also inhibits the norepinephrine transporter. The strong H1 antagonism drives sedation; 5-HT2A/D2 ratio contributes to atypical antipsychotic profile.',
    absorption: 'Rapidly absorbed after oral administration. Tmax ~1.5 hours (IR), ~6 hours (XR). Bioavailability ~100% relative to oral solution. Food increases Cmax by ~25% for IR; high-fat food increases XR Cmax and AUC.',
    volumeOfDistribution: '~10 L/kg',
    proteinBinding: '~83%',
    metabolism: 'Extensively metabolized hepatically via CYP3A4 (primary) to the active metabolite norquetiapine and inactive sulfoxide metabolite.',
    routeOfElimination: 'Renal (~73%) and fecal (~20%). Less than 1% excreted unchanged.',
    clearance: '~100 L/hr (apparent oral clearance)',
    toxicity: 'Metabolic syndrome (weight gain, dyslipidemia, hyperglycemia, diabetes). Orthostatic hypotension. QT prolongation. Somnolence. Tardive dyskinesia with long-term use.',
    foodInteractions: [
      'High-fat meals increase XR formulation absorption',
      'Avoid alcohol (additive CNS depression)',
      'Grapefruit juice may increase levels via CYP3A4 inhibition',
    ],
    drugInteractions: [
      'CYP3A4 inhibitors (ketoconazole, erythromycin, nefazodone) significantly increase quetiapine levels — reduce quetiapine dose',
      'CYP3A4 inducers (phenytoin, carbamazepine, rifampin) decrease quetiapine levels significantly',
      'CNS depressants — additive sedation',
      'Anticholinergic drugs — additive effects',
      'QT-prolonging drugs — use cautiously',
      'Dopamine agonists and levodopa — quetiapine may antagonize effects',
    ],
    contraindications: [
      'Known hypersensitivity to quetiapine',
    ],
    availableFormulations: [
      'Immediate-release tablets: 25mg, 50mg, 100mg, 200mg, 300mg, 400mg',
      'Extended-release tablets (XR): 50mg, 150mg, 200mg, 300mg, 400mg',
    ],
    fdaApprovalYear: 1997,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Increased mortality in elderly patients with dementia-related psychosis. Suicidality risk in children, adolescents, and young adults (for MDD adjunct indication).',
  },
  risperdal: {
    name: 'Risperdal',
    generic: 'risperidone',
    class: 'Atypical Antipsychotic',
    slug: 'risperdal',
    halfLife: '3–20 hours',
    commonDoses: '0.5mg, 1mg, 2mg, 3mg, 4mg',
    taperNotes: 'Liquid formulation (1mg/mL) available for precise dosing. Withdrawal can include supersensitivity psychosis.',
    withdrawalSymptoms: ['insomnia', 'nausea', 'anxiety', 'psychosis risk', 'movement disorders'],
    maudsleyGuidance: 'Oral solution provides precise dosing. Extremely gradual taper essential, especially for long-term use. Risk of dopamine supersensitivity.',
    color: '#ea580c',
    description: 'Risperidone is an atypical antipsychotic approved for schizophrenia, bipolar mania, and irritability associated with autistic disorder. It has high affinity for dopamine D2 and serotonin 5-HT2A receptors and carries a notable risk of hyperprolactinemia.',
    mechanismOfAction: 'Potent antagonist at dopamine D2 and serotonin 5-HT2A receptors. Also antagonizes alpha-1, alpha-2 adrenergic, and histamine H1 receptors. Higher D2 affinity than most atypicals contributes to EPS risk at higher doses and hyperprolactinemia.',
    absorption: 'Well absorbed after oral administration. Bioavailability ~70% (oral solution) to ~66% (tablets). Tmax ~1 hour. Food does not significantly affect absorption.',
    volumeOfDistribution: '~1–2 L/kg',
    proteinBinding: '~90% (risperidone), ~77% (9-hydroxyrisperidone)',
    metabolism: 'Hepatic via CYP2D6 (primary) to the active metabolite 9-hydroxyrisperidone (paliperidone), which has similar pharmacological activity. CYP3A4 is a minor pathway.',
    routeOfElimination: 'Renal (~70%) and fecal (~14%). In extensive CYP2D6 metabolizers, active moiety (risperidone + 9-OH-risperidone) half-life is ~20 hours.',
    clearance: '~5–8 mL/min/kg (total active moiety clearance)',
    toxicity: 'Hyperprolactinemia (highest among atypicals). Extrapyramidal symptoms at higher doses. Metabolic effects (weight gain, hyperglycemia, dyslipidemia). Orthostatic hypotension. Tardive dyskinesia. NMS rarely.',
    foodInteractions: [
      'Food does not significantly affect absorption',
      'Avoid alcohol (additive CNS depression)',
    ],
    drugInteractions: [
      'CYP2D6 inhibitors (fluoxetine, paroxetine) increase risperidone levels',
      'CYP3A4 inducers (carbamazepine, phenytoin, rifampin) decrease risperidone levels',
      'CYP3A4 inhibitors (ketoconazole, itraconazole) increase risperidone levels',
      'CNS depressants — additive sedation',
      'Dopamine agonists and levodopa — risperidone may antagonize effects',
      'QT-prolonging drugs — use cautiously',
      'Antihypertensives — additive hypotension',
    ],
    contraindications: [
      'Known hypersensitivity to risperidone or paliperidone',
    ],
    availableFormulations: [
      'Tablets: 0.25mg, 0.5mg, 1mg, 2mg, 3mg, 4mg',
      'Orally disintegrating tablets (M-Tab): 0.25mg, 0.5mg, 1mg, 2mg, 3mg, 4mg',
      'Oral solution: 1mg/mL',
      'Long-acting injection (Risperdal Consta): 12.5mg, 25mg, 37.5mg, 50mg',
    ],
    fdaApprovalYear: 1993,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Increased mortality in elderly patients with dementia-related psychosis.',
  },
  abilify: {
    name: 'Abilify',
    generic: 'aripiprazole',
    class: 'Atypical Antipsychotic',
    slug: 'abilify',
    halfLife: '75–94 hours',
    commonDoses: '2mg, 5mg, 10mg, 15mg, 20mg, 30mg',
    taperNotes: 'Very long half-life. Liquid formulation (1mg/mL) available. Often used as adjunct to antidepressants.',
    withdrawalSymptoms: ['insomnia', 'anxiety', 'nausea', 'irritability', 'akathisia'],
    maudsleyGuidance: 'Long half-life provides some buffering. Oral solution (1mg/mL) allows precise reductions. Reduce gradually despite long half-life.',
    color: '#dc2626',
    description: 'Aripiprazole is an atypical antipsychotic with a unique mechanism as a partial agonist at dopamine D2 receptors. It is approved for schizophrenia, bipolar I disorder, adjunctive treatment of MDD, irritability in autism, and Tourette disorder.',
    mechanismOfAction: 'Partial agonist at dopamine D2 and serotonin 5-HT1A receptors, and antagonist at serotonin 5-HT2A receptors. This unique "dopamine stabilizer" profile means it can act as a functional antagonist in hyperdopaminergic states and a functional agonist in hypodopaminergic states.',
    absorption: 'Well absorbed after oral administration. Bioavailability ~87%. Tmax 3–5 hours. Food does not significantly affect absorption.',
    volumeOfDistribution: '~4.9 L/kg',
    proteinBinding: '>99% (primarily albumin)',
    metabolism: 'Hepatic via CYP3A4 and CYP2D6 to the active metabolite dehydro-aripiprazole, which has similar D2 receptor affinity. Dehydro-aripiprazole represents ~40% of parent drug AUC in plasma.',
    routeOfElimination: 'Fecal (~55%) and renal (~25%). Less than 1% excreted unchanged in urine.',
    clearance: '~3.5 mL/min/kg',
    toxicity: 'Akathisia is the most common dose-limiting side effect. Less metabolic burden than other atypicals (lower weight gain, lipid changes). Compulsive behaviors (gambling, eating, shopping) reported. NMS and tardive dyskinesia rare.',
    foodInteractions: [
      'Food does not affect absorption',
      'Avoid alcohol (additive CNS depression)',
    ],
    drugInteractions: [
      'CYP2D6 inhibitors (fluoxetine, paroxetine) increase aripiprazole levels — reduce aripiprazole dose by 50%',
      'CYP3A4 inhibitors (ketoconazole, itraconazole) increase aripiprazole levels — reduce dose by 50%',
      'CYP3A4 inducers (carbamazepine, rifampin) decrease aripiprazole levels — double dose when co-administered',
      'CNS depressants — additive sedation',
      'Antihypertensives — additive hypotension',
    ],
    contraindications: [
      'Known hypersensitivity to aripiprazole',
    ],
    availableFormulations: [
      'Tablets: 2mg, 5mg, 10mg, 15mg, 20mg, 30mg',
      'Orally disintegrating tablets: 10mg, 15mg',
      'Oral solution: 1mg/mL',
      'Intramuscular injection: 9.75mg/1.3mL',
      'Extended-release injection (Abilify Maintena): 300mg, 400mg',
    ],
    fdaApprovalYear: 2002,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Increased mortality in elderly patients with dementia-related psychosis. Suicidality risk in children, adolescents, and young adults (for MDD adjunct indication).',
  },
  zyprexa: {
    name: 'Zyprexa',
    generic: 'olanzapine',
    class: 'Atypical Antipsychotic',
    slug: 'zyprexa',
    halfLife: '21–54 hours',
    commonDoses: '2.5mg, 5mg, 10mg, 15mg, 20mg',
    taperNotes: 'Tablets can be split. Weight gain reversal during tapering. Rebound insomnia common.',
    withdrawalSymptoms: ['rebound insomnia', 'anxiety', 'nausea', 'psychosis risk', 'sweating'],
    maudsleyGuidance: 'Slow gradual taper essential. Tablets available in small increments (2.5mg). Monitor for supersensitivity symptoms.',
    color: '#b91c1c',
    description: 'Olanzapine is an atypical antipsychotic approved for schizophrenia and bipolar disorder (manic/mixed episodes, maintenance, and bipolar depression in combination with fluoxetine). It is effective but carries the highest metabolic risk among atypical antipsychotics.',
    mechanismOfAction: 'Antagonist at dopamine D1–D4, serotonin 5-HT2A/2C/3/6, histamine H1, muscarinic M1–M5, and alpha-1 adrenergic receptors. The broad receptor profile contributes to efficacy but also drives significant weight gain and metabolic effects.',
    absorption: 'Well absorbed after oral administration. Bioavailability ~60% due to first-pass metabolism. Tmax ~6 hours. Food does not significantly affect absorption.',
    volumeOfDistribution: '~1000 L (~14 L/kg)',
    proteinBinding: '~93%',
    metabolism: 'Extensively metabolized hepatically via CYP1A2 (primary) and CYP2D6 via glucuronidation and oxidation. Major metabolites (10-N-glucuronide and 4\'-N-desmethyl) are inactive.',
    routeOfElimination: 'Renal (~57%) and fecal (~30%). Approximately 7% excreted unchanged in urine.',
    clearance: '~26 L/hr (apparent oral clearance)',
    toxicity: 'Significant metabolic syndrome (weight gain, hyperglycemia, diabetes, dyslipidemia — highest among atypical antipsychotics). Sedation. Orthostatic hypotension. Tardive dyskinesia. NMS rarely.',
    foodInteractions: [
      'Food does not significantly affect absorption',
      'Avoid alcohol (additive CNS depression)',
    ],
    drugInteractions: [
      'CYP1A2 inhibitors (fluvoxamine, ciprofloxacin) increase olanzapine levels — reduce dose',
      'CYP1A2 inducers (smoking, carbamazepine) decrease olanzapine levels — dose adjustment needed (smokers need higher doses)',
      'CNS depressants — additive sedation',
      'Anticholinergic drugs — additive anticholinergic effects',
      'Dopamine agonists and levodopa — olanzapine may antagonize effects',
      'Antihypertensives — additive hypotension',
    ],
    contraindications: [
      'Known hypersensitivity to olanzapine',
    ],
    availableFormulations: [
      'Tablets: 2.5mg, 5mg, 7.5mg, 10mg, 15mg, 20mg',
      'Orally disintegrating tablets (Zydis): 5mg, 10mg, 15mg, 20mg',
      'Intramuscular injection: 10mg',
      'Extended-release injection (Zyprexa Relprevv): 210mg, 300mg, 405mg',
    ],
    fdaApprovalYear: 1996,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Increased mortality in elderly patients with dementia-related psychosis. Post-injection delirium/sedation syndrome with extended-release IM formulation (Zyprexa Relprevv).',
  },

  // Benzodiazepines
  klonopin: {
    name: 'Klonopin',
    generic: 'clonazepam',
    class: 'Benzodiazepine',
    slug: 'klonopin',
    halfLife: '18–50 hours',
    commonDoses: '0.25mg, 0.5mg, 1mg, 2mg',
    taperNotes: 'Long-acting benzodiazepine. Ashton Manual is the gold-standard tapering resource. Tablets can be split and dissolved in water for micro-tapering.',
    withdrawalSymptoms: ['anxiety', 'insomnia', 'seizure risk', 'muscle tension', 'depersonalization', 'tinnitus', 'sensory hypersensitivity'],
    maudsleyGuidance: 'Follow Ashton Manual protocols. Consider crossover to diazepam for smoother taper. Never stop abruptly — seizure risk.',
    color: '#7c3aed',
    description: 'Clonazepam is a long-acting benzodiazepine approved for seizure disorders and panic disorder. It is widely used off-label for anxiety and insomnia. It has a high potency relative to other benzodiazepines (0.5mg clonazepam ≈ 10mg diazepam).',
    mechanismOfAction: 'Positive allosteric modulator at GABA-A receptors, binding to the benzodiazepine site and enhancing the effect of GABA. This increases chloride ion conductance, resulting in neuronal hyperpolarization and CNS depression. Also has serotonergic activity that may contribute to its anti-panic effects.',
    absorption: 'Rapidly and completely absorbed after oral administration. Bioavailability ~90%. Tmax 1–4 hours. Food does not significantly affect absorption.',
    volumeOfDistribution: '~3.2 L/kg',
    proteinBinding: '~85%',
    metabolism: 'Hepatic via CYP3A4 to the inactive metabolite 7-aminoclonazepam (via nitroreduction) and other hydroxylated metabolites. Acetylation of 7-aminoclonazepam also occurs.',
    routeOfElimination: 'Renal (~50–70% as metabolites). Less than 2% excreted unchanged in urine.',
    clearance: '~55 mL/min (total body clearance)',
    toxicity: 'CNS depression, respiratory depression (especially combined with opioids/alcohol). Physical dependence develops with chronic use. Abrupt discontinuation can cause seizures, delirium tremens-like syndrome, and death.',
    foodInteractions: [
      'Food does not significantly affect absorption',
      'Avoid alcohol (additive CNS depression, potentially fatal respiratory depression)',
      'Avoid grapefruit juice (may increase levels via CYP3A4 inhibition)',
    ],
    drugInteractions: [
      'Opioids — FDA boxed warning: concurrent use increases risk of profound sedation, respiratory depression, coma, and death',
      'CNS depressants (alcohol, barbiturates, other benzodiazepines) — additive respiratory depression',
      'CYP3A4 inhibitors (ketoconazole, itraconazole) may increase clonazepam levels',
      'CYP3A4 inducers (phenytoin, carbamazepine, rifampin) may decrease clonazepam levels',
    ],
    contraindications: [
      'Significant hepatic disease',
      'Acute narrow-angle glaucoma',
      'Known hypersensitivity to clonazepam or other benzodiazepines',
    ],
    availableFormulations: [
      'Tablets: 0.5mg, 1mg, 2mg',
      'Orally disintegrating tablets: 0.125mg, 0.25mg, 0.5mg, 1mg, 2mg',
    ],
    fdaApprovalYear: 1975,
    pregnancyCategory: 'Category D (positive evidence of risk)',
    blackBoxWarning: 'Concomitant use with opioids may result in profound sedation, respiratory depression, coma, and death. Risks of abuse, misuse, and addiction, which can lead to overdose and death. Physical dependence and life-threatening withdrawal reactions.',
  },
  ativan: {
    name: 'Ativan',
    generic: 'lorazepam',
    class: 'Benzodiazepine',
    slug: 'ativan',
    halfLife: '10–20 hours',
    commonDoses: '0.5mg, 1mg, 2mg',
    taperNotes: 'Medium half-life benzo. Crossover to diazepam often recommended for smoother taper. Liquid formulation available.',
    withdrawalSymptoms: ['anxiety', 'insomnia', 'seizure risk', 'tremor', 'sweating', 'sensory disturbances'],
    maudsleyGuidance: 'Ashton Manual recommends crossover to diazepam for gradual taper. Never stop abruptly — seizure risk.',
    color: '#6d28d9',
    description: 'Lorazepam is an intermediate-acting benzodiazepine approved for anxiety disorders and as a pre-anesthetic. It has no active metabolites and is metabolized by glucuronidation, making it preferred in patients with hepatic impairment or in the elderly.',
    mechanismOfAction: 'Positive allosteric modulator at GABA-A receptors. Binds to the benzodiazepine site and enhances GABA-mediated chloride conductance, producing anxiolytic, sedative, hypnotic, anticonvulsant, and muscle relaxant effects.',
    absorption: 'Well absorbed after oral administration. Bioavailability ~90%. Tmax ~2 hours. Food may slow absorption but does not reduce bioavailability.',
    volumeOfDistribution: '~1.3 L/kg',
    proteinBinding: '~85%',
    metabolism: 'Hepatic via glucuronidation (UGT) to the inactive lorazepam glucuronide. Does NOT undergo CYP-mediated oxidative metabolism, making it preferred in hepatic impairment.',
    routeOfElimination: 'Renal (~88% as glucuronide conjugate). Less than 1% excreted unchanged in urine.',
    clearance: '~1.1 mL/min/kg',
    toxicity: 'CNS and respiratory depression, especially with opioids or alcohol. Physical dependence with chronic use. Abrupt discontinuation can cause seizures, psychosis, and death.',
    foodInteractions: [
      'Food may slow absorption rate but does not reduce total bioavailability',
      'Avoid alcohol (additive CNS and respiratory depression, potentially fatal)',
    ],
    drugInteractions: [
      'Opioids — FDA boxed warning: concurrent use increases risk of profound sedation, respiratory depression, coma, and death',
      'CNS depressants (alcohol, barbiturates, other sedatives) — additive respiratory depression',
      'Probenecid and valproate may increase lorazepam levels (inhibit glucuronidation)',
      'Minimal CYP-based interactions (advantage in polypharmacy)',
    ],
    contraindications: [
      'Acute narrow-angle glaucoma',
      'Known hypersensitivity to lorazepam or other benzodiazepines',
      'Intra-arterial injection (parenteral formulation)',
    ],
    availableFormulations: [
      'Tablets: 0.5mg, 1mg, 2mg',
      'Oral concentrate: 2mg/mL',
      'Injection: 2mg/mL, 4mg/mL',
    ],
    fdaApprovalYear: 1977,
    pregnancyCategory: 'Category D (positive evidence of risk)',
    blackBoxWarning: 'Concomitant use with opioids may result in profound sedation, respiratory depression, coma, and death. Risks of abuse, misuse, and addiction, which can lead to overdose and death. Physical dependence and life-threatening withdrawal reactions.',
  },
  xanax: {
    name: 'Xanax',
    generic: 'alprazolam',
    class: 'Benzodiazepine',
    slug: 'xanax',
    halfLife: '6–12 hours',
    commonDoses: '0.25mg, 0.5mg, 1mg, 2mg',
    taperNotes: 'Very short half-life makes this the hardest benzodiazepine to taper. Inter-dose withdrawal common. Crossover to diazepam strongly recommended.',
    withdrawalSymptoms: ['severe anxiety', 'insomnia', 'seizure risk', 'panic attacks', 'tremor', 'depersonalization'],
    maudsleyGuidance: 'Crossover to diazepam essential for safe taper. Very short half-life causes interdose withdrawal. Never stop abruptly.',
    color: '#4c1d95',
    description: 'Alprazolam is a short-acting, high-potency benzodiazepine approved for anxiety disorders and panic disorder. It is the most commonly prescribed benzodiazepine in the US and has the highest abuse potential among benzodiazepines due to rapid onset and short duration.',
    mechanismOfAction: 'Positive allosteric modulator at GABA-A receptors. Binds to the benzodiazepine site, enhancing GABA-mediated inhibition. Its rapid onset and short half-life contribute to both its anxiolytic efficacy and high dependence liability.',
    absorption: 'Rapidly absorbed after oral administration. Bioavailability ~80–90%. Tmax 1–2 hours (IR), ~11 hours (XR). Food does not significantly affect total absorption.',
    volumeOfDistribution: '~0.9–1.2 L/kg',
    proteinBinding: '~80%',
    metabolism: 'Hepatic via CYP3A4 (primary) to alpha-hydroxyalprazolam (weakly active) and a benzophenone derivative (inactive).',
    routeOfElimination: 'Renal (~80% as metabolites). Less than 20% excreted unchanged in urine.',
    clearance: '~1.0–1.3 mL/min/kg',
    toxicity: 'Severe CNS and respiratory depression (especially with opioids/alcohol). Extremely high physical dependence potential. Withdrawal seizures and death possible with abrupt discontinuation. Rebound anxiety between doses.',
    foodInteractions: [
      'Food does not significantly affect absorption',
      'Avoid alcohol (additive CNS and respiratory depression, potentially fatal)',
      'Grapefruit juice increases levels via CYP3A4 inhibition',
    ],
    drugInteractions: [
      'Opioids — FDA boxed warning: concurrent use increases risk of profound sedation, respiratory depression, coma, and death',
      'CYP3A4 inhibitors (ketoconazole, itraconazole, nefazodone, fluvoxamine) significantly increase alprazolam levels',
      'CYP3A4 inducers (carbamazepine, rifampin) decrease alprazolam levels',
      'CNS depressants — additive respiratory and CNS depression',
      'Nefazodone — contraindicated (2-fold increase in alprazolam levels)',
    ],
    contraindications: [
      'Acute narrow-angle glaucoma',
      'Concurrent ketoconazole or itraconazole',
      'Known hypersensitivity to alprazolam or other benzodiazepines',
    ],
    availableFormulations: [
      'Tablets: 0.25mg, 0.5mg, 1mg, 2mg',
      'Extended-release tablets (XR): 0.5mg, 1mg, 2mg, 3mg',
      'Orally disintegrating tablets: 0.25mg, 0.5mg, 1mg, 2mg',
      'Oral concentrate: 1mg/mL',
    ],
    fdaApprovalYear: 1981,
    pregnancyCategory: 'Category D (positive evidence of risk)',
    blackBoxWarning: 'Concomitant use with opioids may result in profound sedation, respiratory depression, coma, and death. Risks of abuse, misuse, and addiction, which can lead to overdose and death. Physical dependence and life-threatening withdrawal reactions.',
  },
  valium: {
    name: 'Valium',
    generic: 'diazepam',
    class: 'Benzodiazepine',
    slug: 'valium',
    halfLife: '20–100 hours',
    commonDoses: '2mg, 5mg, 10mg',
    taperNotes: 'Very long half-life — often used as the target drug for benzodiazepine crossover tapers. Tablets easily split. Liquid formulation available.',
    withdrawalSymptoms: ['anxiety', 'insomnia', 'muscle tension', 'sensory sensitivity', 'depersonalization'],
    maudsleyGuidance: 'Preferred benzodiazepine for tapering due to long half-life and available small doses. Ashton Manual taper schedules use diazepam as the standard.',
    color: '#5b21b6',
    description: 'Diazepam is a long-acting benzodiazepine approved for anxiety disorders, alcohol withdrawal, muscle spasm, seizures, and as a pre-anesthetic. Due to its long half-life, multiple tablet strengths, and smooth pharmacokinetic profile, it is the preferred benzodiazepine for crossover tapers.',
    mechanismOfAction: 'Positive allosteric modulator at GABA-A receptors. Enhances GABA-mediated chloride conductance producing anxiolytic, sedative, anticonvulsant, and muscle relaxant effects. Multiple active metabolites (desmethyldiazepam, temazepam, oxazepam) prolong its duration of action.',
    absorption: 'Rapidly and completely absorbed after oral administration. Bioavailability ~100%. Tmax 0.5–2 hours. Food may delay absorption.',
    volumeOfDistribution: '~0.8–1.0 L/kg',
    proteinBinding: '~98%',
    metabolism: 'Hepatic via CYP3A4 and CYP2C19 to the long-acting active metabolite desmethyldiazepam (half-life 36–200 hours), then to oxazepam, and via CYP3A4 to temazepam (both active). Final elimination via glucuronidation.',
    routeOfElimination: 'Renal (primarily as glucuronide conjugates of metabolites). Very little unchanged diazepam in urine.',
    clearance: '~20–30 mL/min (total body clearance)',
    toxicity: 'CNS and respiratory depression (especially with opioids/alcohol). Physical dependence with chronic use. Extremely long effective half-life due to active metabolites can lead to accumulation in elderly. Abrupt discontinuation can cause seizures.',
    foodInteractions: [
      'Food may delay absorption but does not reduce bioavailability',
      'Avoid alcohol (additive CNS and respiratory depression, potentially fatal)',
      'Grapefruit juice may increase levels via CYP3A4 inhibition',
    ],
    drugInteractions: [
      'Opioids — FDA boxed warning: concurrent use increases risk of profound sedation, respiratory depression, coma, and death',
      'CYP3A4 inhibitors (ketoconazole, fluvoxamine) increase diazepam levels',
      'CYP2C19 inhibitors (omeprazole, fluvoxamine) increase diazepam levels',
      'CYP3A4 inducers (rifampin) decrease diazepam levels',
      'CNS depressants — additive respiratory and CNS depression',
      'Cimetidine increases diazepam levels',
    ],
    contraindications: [
      'Acute narrow-angle glaucoma',
      'Myasthenia gravis',
      'Severe respiratory insufficiency',
      'Severe hepatic insufficiency',
      'Sleep apnea syndrome',
      'Known hypersensitivity to diazepam or other benzodiazepines',
    ],
    availableFormulations: [
      'Tablets: 2mg, 5mg, 10mg',
      'Oral solution: 5mg/5mL',
      'Oral concentrate (Intensol): 5mg/mL',
      'Injection: 5mg/mL',
      'Rectal gel (Diastat): 2.5mg, 10mg, 20mg',
    ],
    fdaApprovalYear: 1963,
    pregnancyCategory: 'Category D (positive evidence of risk)',
    blackBoxWarning: 'Concomitant use with opioids may result in profound sedation, respiratory depression, coma, and death. Risks of abuse, misuse, and addiction, which can lead to overdose and death. Physical dependence and life-threatening withdrawal reactions.',
  },

  // Gabapentinoids
  gabapentin: {
    name: 'Gabapentin',
    generic: 'gabapentin',
    class: 'Gabapentinoid',
    slug: 'gabapentin',
    halfLife: '5–7 hours',
    commonDoses: '100mg, 300mg, 600mg, 800mg',
    taperNotes: 'Short half-life with non-linear absorption. Multiple daily doses needed. Water titration method works well for precise reductions.',
    withdrawalSymptoms: ['anxiety', 'insomnia', 'nausea', 'sweating', 'seizure risk at high doses', 'pain rebound'],
    maudsleyGuidance: 'Reduce by no more than 10% per step. Non-linear pharmacokinetics mean absorption decreases at higher doses. Capsules can be opened for water titration.',
    color: '#059669',
    description: 'Gabapentin is an anticonvulsant approved for epilepsy (adjunctive therapy for partial seizures) and postherpetic neuralgia. It is widely prescribed off-label for neuropathic pain, anxiety, insomnia, and alcohol/benzodiazepine withdrawal. Despite its name, it does not bind GABA receptors.',
    mechanismOfAction: 'Binds to the alpha-2-delta subunit of voltage-gated calcium channels, reducing calcium influx and subsequent release of excitatory neurotransmitters (glutamate, norepinephrine, substance P). Does not bind GABA receptors or affect GABA uptake/metabolism.',
    absorption: 'Absorbed via L-amino acid transport system in the small intestine. Bioavailability is dose-dependent (inversely proportional): ~60% at 300mg, ~35% at 1600mg. Tmax 2–3 hours. Food modestly increases absorption.',
    volumeOfDistribution: '~0.8 L/kg (58 L in 72 kg individual)',
    proteinBinding: '<3% (not significantly protein bound)',
    metabolism: 'Not appreciably metabolized in humans. No CYP involvement. Excreted unchanged.',
    routeOfElimination: 'Renal (~100% excreted unchanged). Clearance is proportional to creatinine clearance.',
    clearance: '~120–130 mL/min (renal clearance, similar to GFR)',
    toxicity: 'Relatively low acute toxicity. Respiratory depression when combined with opioids or CNS depressants. Suicidal ideation (class warning for anticonvulsants). Physical dependence with chronic high-dose use.',
    foodInteractions: [
      'Food modestly increases absorption (~14%)',
      'Avoid alcohol (additive CNS depression)',
    ],
    drugInteractions: [
      'Opioids — increased risk of respiratory depression and sedation',
      'CNS depressants — additive sedation',
      'Antacids containing aluminum/magnesium reduce gabapentin absorption by ~20% — dose gabapentin ≥2 hours after antacids',
      'Morphine increases gabapentin levels (~44%)',
      'Minimal CYP-based drug interactions (advantage)',
    ],
    contraindications: [
      'Known hypersensitivity to gabapentin',
    ],
    availableFormulations: [
      'Capsules: 100mg, 300mg, 400mg',
      'Tablets: 600mg, 800mg',
      'Oral solution: 250mg/5mL',
      'Extended-release tablets (Gralise): 300mg, 600mg',
    ],
    fdaApprovalYear: 1993,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Respiratory depression risk when used with CNS depressants, particularly opioids. Increased risk of suicidal thoughts and behavior (anticonvulsant class warning).',
  },
  lyrica: {
    name: 'Lyrica',
    generic: 'pregabalin',
    class: 'Gabapentinoid',
    slug: 'lyrica',
    halfLife: '6 hours',
    commonDoses: '25mg, 50mg, 75mg, 150mg, 300mg',
    taperNotes: 'Linear absorption unlike gabapentin. Short half-life requires slow taper. Capsules can be opened for precise dosing.',
    withdrawalSymptoms: ['anxiety', 'insomnia', 'sweating', 'nausea', 'headache', 'seizure risk'],
    maudsleyGuidance: 'Linear pharmacokinetics but short half-life. Gradual reduction essential. Capsule contents can be weighed for precise reductions.',
    color: '#047857',
    description: 'Pregabalin is a gabapentinoid approved for neuropathic pain (diabetic peripheral neuropathy, postherpetic neuralgia), fibromyalgia, partial-onset seizures (adjunctive), and spinal cord injury neuropathic pain. It is a Schedule V controlled substance due to abuse potential.',
    mechanismOfAction: 'Binds potently to the alpha-2-delta subunit of voltage-gated calcium channels, reducing excitatory neurotransmitter release. Similar mechanism to gabapentin but with 6-fold higher binding affinity. Does not bind GABA receptors.',
    absorption: 'Rapidly absorbed with linear, dose-proportional pharmacokinetics (unlike gabapentin). Bioavailability ≥90%. Tmax ~1.5 hours. Food decreases Cmax by ~25% and delays Tmax but does not reduce total absorption.',
    volumeOfDistribution: '~0.5 L/kg',
    proteinBinding: 'Not significantly bound to plasma proteins',
    metabolism: 'Negligible metabolism in humans (<2% of dose). No CYP involvement. N-methylated metabolite is the only identified metabolite.',
    routeOfElimination: 'Renal (~90% excreted unchanged). Clearance proportional to creatinine clearance.',
    clearance: '~67–80 mL/min (renal clearance)',
    toxicity: 'Dizziness and somnolence most common. Respiratory depression with CNS depressants/opioids. Physical dependence with chronic use. Euphoria/misuse potential (Schedule V). Suicidal ideation (anticonvulsant class warning). Angioedema rarely reported.',
    foodInteractions: [
      'Food reduces peak concentration but does not affect total absorption',
      'Avoid alcohol (additive CNS depression)',
    ],
    drugInteractions: [
      'Opioids — increased risk of respiratory depression and sedation',
      'CNS depressants (benzodiazepines, alcohol, barbiturates) — additive sedation and respiratory depression',
      'ACE inhibitors — pregabalin may increase risk of angioedema',
      'Thiazolidinediones (pioglitazone, rosiglitazone) — additive weight gain and edema',
      'Minimal CYP-based drug interactions',
    ],
    contraindications: [
      'Known hypersensitivity to pregabalin (angioedema and hypersensitivity reactions reported)',
    ],
    availableFormulations: [
      'Capsules: 25mg, 50mg, 75mg, 100mg, 150mg, 200mg, 225mg, 300mg',
      'Oral solution: 20mg/mL',
      'Extended-release tablets (Lyrica CR): 82.5mg, 165mg, 330mg',
    ],
    fdaApprovalYear: 2004,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Respiratory depression risk when used with CNS depressants, particularly opioids. Increased risk of suicidal thoughts and behavior (anticonvulsant class warning).',
  },

  // Other
  trazodone: {
    name: 'Trazodone',
    generic: 'trazodone',
    class: 'Other',
    slug: 'trazodone',
    halfLife: '5–9 hours',
    commonDoses: '25mg, 50mg, 100mg, 150mg',
    taperNotes: 'Often prescribed for insomnia at low doses. Rebound insomnia is the most common withdrawal symptom. Tablets can be split.',
    withdrawalSymptoms: ['rebound insomnia', 'anxiety', 'irritability', 'nausea'],
    maudsleyGuidance: 'When used for sleep at low doses, taper gradually to minimize rebound insomnia. Tablets can be split for small reductions.',
    color: '#0d9488',
    description: 'Trazodone is a serotonin antagonist and reuptake inhibitor (SARI) approved for major depressive disorder. At antidepressant doses (150–600mg), it modulates serotonin; at lower doses (25–100mg), its potent H1 and 5-HT2A antagonism provides sedation, making it one of the most commonly prescribed sleep aids.',
    mechanismOfAction: 'Serotonin antagonist and reuptake inhibitor (SARI). Blocks 5-HT2A receptors, weakly inhibits serotonin reuptake, and antagonizes histamine H1 and alpha-1 adrenergic receptors. The active metabolite mCPP is a 5-HT2C agonist. At low doses, H1 and 5-HT2A antagonism predominate.',
    absorption: 'Well absorbed after oral administration. Bioavailability ~65–80%. Tmax ~1 hour (fasting), ~2 hours (with food). Food increases Cmax and AUC; take shortly after meals.',
    volumeOfDistribution: '~0.8–1.5 L/kg',
    proteinBinding: '~89–95%',
    metabolism: 'Hepatic via CYP3A4 (primary) to the active metabolite meta-chlorophenylpiperazine (mCPP). Further metabolism produces inactive conjugated metabolites.',
    routeOfElimination: 'Renal (~70–75% as metabolites) and fecal (~21%). Less than 1% excreted unchanged.',
    clearance: '~110–230 mL/min (apparent oral clearance)',
    toxicity: 'Priapism (rare but serious — requires immediate medical attention). Orthostatic hypotension. QT prolongation at high doses or in overdose. Serotonin syndrome with serotonergic combinations. Relatively low toxicity in overdose compared to TCAs.',
    foodInteractions: [
      'Food increases absorption; take shortly after a meal or snack',
      'Avoid alcohol (additive CNS depression)',
    ],
    drugInteractions: [
      'MAOIs — contraindicated (serotonin syndrome risk)',
      'CYP3A4 inhibitors (ketoconazole, ritonavir) increase trazodone levels — consider dose reduction',
      'CYP3A4 inducers (carbamazepine) decrease trazodone levels',
      'Serotonergic drugs increase serotonin syndrome risk',
      'CNS depressants — additive sedation',
      'QT-prolonging drugs — use cautiously',
      'Digoxin and phenytoin levels may be increased',
    ],
    contraindications: [
      'MAOIs within 14 days',
      'Known hypersensitivity to trazodone',
    ],
    availableFormulations: [
      'Tablets: 50mg, 100mg, 150mg, 300mg',
      'Extended-release tablets (Oleptro): 150mg, 300mg',
    ],
    fdaApprovalYear: 1981,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Suicidality risk in children, adolescents, and young adults under 25 during initial treatment.',
  },
  lamictal: {
    name: 'Lamictal',
    generic: 'lamotrigine',
    class: 'Other',
    slug: 'lamictal',
    halfLife: '25–33 hours',
    commonDoses: '25mg, 50mg, 100mg, 200mg',
    taperNotes: 'Used as mood stabilizer. Must taper slowly — if stopped and restarted, must re-titrate from scratch due to SJS risk. Available in chewable/dispersible tablets.',
    withdrawalSymptoms: ['seizure risk', 'mood instability', 'anxiety', 'insomnia', 'irritability'],
    maudsleyGuidance: 'Gradual taper essential. If a dose is missed for >5 days, re-titration from low dose is required due to serious rash risk (SJS). Chewable tablets allow fine dose adjustments.',
    color: '#0891b2',
    description: 'Lamotrigine is an anticonvulsant approved for epilepsy (partial seizures, primary generalized tonic-clonic seizures, Lennox-Gastaut syndrome) and maintenance treatment of bipolar I disorder. It is the only mood stabilizer with strong evidence for preventing bipolar depression.',
    mechanismOfAction: 'Blocks voltage-sensitive sodium channels, stabilizing neuronal membranes and inhibiting release of excitatory neurotransmitters (primarily glutamate). May also modulate calcium channels and HCN channels. The anti-glutamate mechanism is thought to underlie its mood-stabilizing effects.',
    absorption: 'Rapidly and completely absorbed after oral administration. Bioavailability ~98%. Tmax ~1.4–4.8 hours. Food does not affect absorption.',
    volumeOfDistribution: '~0.9–1.3 L/kg',
    proteinBinding: '~55%',
    metabolism: 'Hepatic via UGT glucuronidation (primarily UGT1A4). Does not undergo significant CYP metabolism. Valproate inhibits lamotrigine glucuronidation (doubles half-life); enzyme inducers (carbamazepine, phenytoin) accelerate metabolism.',
    routeOfElimination: 'Renal (~94%, with ~10% as unchanged lamotrigine and ~76% as 2-N-glucuronide conjugate). Fecal (~2%).',
    clearance: '~30 mL/min (apparent clearance; varies significantly with co-medications)',
    toxicity: 'Stevens-Johnson syndrome (SJS) and toxic epidermal necrolysis (TEN) — risk highest with rapid titration, concurrent valproate, and in children. Aseptic meningitis. Multiorgan hypersensitivity (DRESS). Suicidal ideation (anticonvulsant class warning).',
    foodInteractions: [
      'Food does not affect absorption',
      'No significant food interactions',
    ],
    drugInteractions: [
      'Valproate significantly increases lamotrigine levels (~2x) by inhibiting glucuronidation — must halve lamotrigine dose',
      'Enzyme inducers (carbamazepine, phenytoin, phenobarbital, primidone, rifampin) decrease lamotrigine levels — dose adjustment needed',
      'Oral contraceptives (estrogen-containing) decrease lamotrigine levels by ~50% — dose adjustment needed during pill-free week',
      'Carbamazepine-lamotrigine combination may increase risk of dizziness, diplopia, ataxia',
    ],
    contraindications: [
      'Known hypersensitivity to lamotrigine',
    ],
    availableFormulations: [
      'Tablets: 25mg, 100mg, 150mg, 200mg',
      'Chewable/dispersible tablets: 2mg, 5mg, 25mg',
      'Orally disintegrating tablets (ODT): 25mg, 50mg, 100mg, 200mg',
      'Extended-release tablets (XR): 25mg, 50mg, 100mg, 200mg, 250mg, 300mg',
    ],
    fdaApprovalYear: 1994,
    pregnancyCategory: 'Category C (risk cannot be ruled out)',
    blackBoxWarning: 'Serious skin rashes including Stevens-Johnson syndrome (SJS) and toxic epidermal necrolysis (TEN), especially during initial titration. Increased risk of suicidal thoughts and behavior (anticonvulsant class warning).',
  },
};

export const DRUG_LIST = Object.values(DRUGS);
export const DRUG_SLUGS = Object.keys(DRUGS);

export function getDrug(slug) {
  return DRUGS[slug] || null;
}

// Group drugs by class for display
export function getDrugsByClass() {
  const grouped = {};
  for (const drug of DRUG_LIST) {
    if (!grouped[drug.class]) {
      grouped[drug.class] = [];
    }
    grouped[drug.class].push(drug);
  }
  return grouped;
}
