-- New York clinician CRM entries — batch 4
-- 16 new entries

INSERT INTO public.clinician_crm (name, credentials, clinic, state, address, phone, email_website, description, source, category, practice_type, status)
VALUES

('Dr. Katherine Falk', 'MD, Board Certified Psychiatry + Integrative Holistic Medicine', 'Private Practice', 'New York', 'Upper East Side, New York City, NY', '(646) 933-0423', 'katherinefalkmd.com', 'Integrative/holistic psychiatrist, 55 years experience. Former Columbia/NYSPI faculty. Uses vitamins, minerals, amino acids, herbs, and homeopathy to minimize or eliminate psychiatric medications. Telepsychiatry available across NY, NJ, CT, CA, IL, MA, PA.', 'psychologytoday.com', 'deprescribing', 'Solo Practice', 'new'),

('Dr. Nivea B. Calico', 'MD, Board Certified Psychiatrist', 'Holistic Wellness Center / East Village Psychiatry', 'New York', '156 Fifth Ave, Suite 1107, New York City, NY', '(347) 218-2908', 'niveacalicomd.com', 'Integrative psychiatrist using psychotherapy, nutritional analysis, acupuncture, traditional Chinese medicine, aromatherapy, meditation, reiki, yoga, sound therapy, and lifestyle modifications. Genesight genetic testing.', 'psychologytoday.com', 'holistic psychiatry', 'Solo Practice', 'new'),

('Dr. Sonya Lazarevic', 'MD, MS, Double Board Certified (Psychiatry + Addiction)', 'Evolution Medicine PC', 'New York', '280 Madison Ave, Midtown, New York City, NY', '(212) 924-2871', 'evo-md.com', 'Combines conventional psychiatry with integrative medicine, nutritional psychiatry, and regenerative medicine. 30+ years in NYC. Specializes in treatment-resistant depression and addiction.', 'zocdoc.com', 'holistic psychiatry', 'Solo Practice', 'new'),

('Dr. Zlatin Ivanov', 'MD, Double Board Certified (Psychiatry + Addiction)', 'Online Psychiatrists / Psychiatrist NYC', 'New York', '405 Lexington Ave, Suite 2601, New York City, NY', '(646) 713-0000', 'onlinepsychiatrists.com', 'Listed on BenzoInfo.com as a Benzodiazepine Cooperative Provider. Integrative approach combining medication management with psychotherapy. Buprenorphine/MAT for addiction. Telepsychiatry available.', 'benzoinfo.com', 'deprescribing', 'Solo Practice', 'new'),

('Dr. Carl Erik Fisher', 'MD, Board Certified Psychiatry + Forensic + Addiction Medicine', 'Private Practice / Columbia University', 'New York', 'Downtown Manhattan & Brooklyn, NY', NULL, 'carlerikfisher.com', 'Columbia-trained addiction psychiatrist with integrative/holistic focus including meditation and yoga. Author of "The Urge: Our History of Addiction." Published in JAMA. Person-centered recovery approach.', 'columbiapsychiatry.org', 'holistic psychiatry', 'Solo Practice', 'new'),

('Jenna Reeder', 'PMHNP-BC, MSN (UCSF), Fellowship in Reproductive & Integrative Psychiatry', 'Brooklyn Integrative Psychiatry', 'New York', 'Brooklyn, NY', '(718) 524-3494', 'bkpsych.com', 'Integrative psychiatric NP combining traditional treatment with IFS, CBT, mindfulness, and relational approaches. Ketamine therapy available. Careful medication monitoring with shared decision-making.', 'bkpsych.com', 'holistic psychiatry', 'Solo Practice', 'new'),

('Dr. Gundu Reddy', 'MD, Board Certified Psychiatrist (Mount Sinai)', 'GABA Telepsychiatry', 'New York', '14 Wall St, 20th Floor, NYC (also serves Poughkeepsie, NY)', NULL, 'gaba.healthcare', 'Holistic approach evaluating physical, nutritional, hormonal, situational, and psychodynamic causes. 15+ years experience. Serves Hudson Valley / Poughkeepsie region via telehealth.', 'psychologytoday.com', 'holistic psychiatry', 'Solo Practice', 'new'),

('Dr. Ryan Sultan', 'MD, Double Board Certified, Assistant Professor Columbia', 'Integrative Psych', 'New York', '80 Eighth Ave, Chelsea, New York City, NY', NULL, 'integrative-psych.org', 'Columbia/Cornell/Emory trained. Combines psychoanalytic background with holistic integrative approach including mindfulness, CBT, and evidence-based Eastern medicine. His JAMA study on antipsychotic prescribing changed national guidelines.', 'integrative-psych.org', 'holistic psychiatry', 'Group Practice', 'new'),

('Dr. Viga Naik', 'MD (New York Medical College / Mount Sinai)', 'New York Integrative Psychiatry', 'New York', 'New York City, NY', '(332) 244-0720', 'nycintegrativepsych.com', 'Adult psychiatrist with specializations in addiction and consultation-liaison psychiatry. Holistic/integrative treatment model beyond psychopharmacology, incorporating psychotherapy and psychosocial intervention.', 'psychologytoday.com', 'holistic psychiatry', 'Group Practice', 'new'),

('Dr. Eugene Osagie', 'MD, Board Certified (Yale/Columbia/Harvard trained)', 'Westchester Integrative Psychiatry PLLC', 'New York', 'White Plains, NY (Westchester)', '(914) 604-3788', NULL, '17+ years experience. Integrative psychiatric care serving adults across New York and Connecticut. Addiction Psychiatry + Obesity Medicine. In-person and telehealth. Accepts Anthem BCBS, UHC, Aetna, Cigna.', 'zocdoc.com', 'holistic psychiatry', 'Solo Practice', 'new'),

('Vera Imperiale', 'PMHNP', 'Kintsugi Integrative Practice', 'New York', '501 New Karner Rd, Suite 9, Albany, NY', '(518) 456-3614', 'kintsugipsych.com', 'Holistic healing and psychotherapy approach. Treats depression, ADHD, anxiety, bipolar, eating disorders, panic disorder. Capital Region practice with evening and crisis hours.', 'kintsugipsych.com', 'holistic psychiatry', 'Solo Practice', 'new'),

('Long Island Mind Medical PLLC', 'Board Certified Psychiatrists (Child & Adult)', 'Long Island Mind Medical PLLC', 'New York', 'Huntington, NY (Suffolk County, Long Island)', '(516) 980-5728', 'longislandmind.com', 'Holistic biopsychosocial model. Treats adults and children ages 5+. Thoughtful, individualized medication management approach. Stony Brook Child Psychiatry fellowship trained.', 'psychologytoday.com', 'holistic psychiatry', 'Group Practice', 'new'),

('Evolve Psychiatry', 'Multiple psychiatrists and PMHNPs', 'Evolve Psychiatry', 'New York', 'Massapequa, Syosset, Garden City, Hauppauge (Long Island) + Albany, NY', NULL, 'evolvepsychiatry.com', 'Comprehensive holistic medication management for all ages. TMS therapy and Spravato available. Multiple Long Island locations plus Albany. Telehealth and in-person.', 'psychologytoday.com', 'holistic psychiatry', 'Group Practice', 'new'),

('Matthew Killian', 'DNP, PMHNP', 'Clarity Psychiatric', 'New York', 'Smithtown, NY (Long Island / Suffolk County)', '(631) 868-5771', NULL, 'Emphasizes empathetic listening, compassion, education, and options. Experience in both private practice and Veterans Health Administration. Evening hours available.', 'psychologytoday.com', 'holistic psychiatry', 'Solo Practice', 'new'),

('Grand Central Psychiatric', 'Board-certified psychiatrists (group)', 'Grand Central Psychiatric', 'New York', 'Grand Central area, New York City, NY', NULL, 'grandcentralpsychiatric.com', 'Holistic approach focusing on short-term relief and long-term wellness. Patient-centered individualized treatment plans. CBT, mindfulness, medication management. Serves all 5 boroughs + NJ + CT.', 'grandcentralpsychiatric.com', 'holistic psychiatry', 'Group Practice', 'new'),

('New York Integrative Psychiatry', 'Psychiatrists, NPs, therapists, nutritionists', 'New York Integrative Psychiatry', 'New York', '111 W 24th St, Suite 300, New York City, NY', '(646) 859-2339', 'nycintegrativepsych.com', 'Multidisciplinary integrative team offering talk therapy, medication management, IM ketamine therapy, and nutrition services. Collaborative approach with psychiatrists, NPs, and nutritionists.', 'nycintegrativepsych.com', 'holistic psychiatry', 'Group Practice', 'new');
