export const DIETS = [
  {
    name: 'Ketogenic',
    slug: 'ketogenic',
    description: 'Very low carb, high fat. The most studied dietary approach for supporting brain recovery during deprescribing.',
    evidence: 'Strong',
    taperingFit: 'High',
    badgeColor: 'indigo',
    details: {
      what: 'The ketogenic diet restricts carbohydrates to under 20g per day, shifting the body into a metabolic state called ketosis. In ketosis, the liver converts fat into ketone bodies, which become the brain\'s primary fuel source instead of glucose.',
      mechanism: 'Ketones are a more efficient and stable fuel for brain cells than glucose. Research suggests ketosis may improve mitochondrial function, reduce neuroinflammation, stabilize neurotransmitter levels, and increase GABA (the brain\'s primary calming neurotransmitter). This is the same mechanism that makes the ketogenic diet effective for epilepsy — a condition it has been used to treat since the 1920s.',
      tapering: 'Many community members report that ketosis helps stabilize mood, reduce anxiety, and improve sleep quality during their taper. The stable energy supply from ketones may buffer against the neurological instability that occurs during medication withdrawal. Some members find that brain fog and irritability — common withdrawal symptoms — are noticeably reduced.',
      considerations: 'The ketogenic diet requires a significant dietary shift and an adaptation period of 1-3 weeks ("keto flu"). It is important not to start keto and a dose reduction at the same time. Electrolyte management is critical. Some people find the diet restrictive — if so, a low-carb approach may be a better starting point.',
    },
    foods: {
      eatFreely: [
        { item: 'Eggs', icon: '🥚' },
        { item: 'Fatty fish (salmon, sardines, mackerel)', icon: '🐟' },
        { item: 'Meat (beef, chicken thighs, pork)', icon: '🥩' },
        { item: 'Butter and ghee', icon: '🧈' },
        { item: 'Olive oil and coconut oil', icon: '🫒' },
        { item: 'Avocados', icon: '🥑' },
        { item: 'Non-starchy vegetables (spinach, broccoli, zucchini)', icon: '🥦' },
        { item: 'Cheese (cheddar, cream cheese, mozzarella)', icon: '🧀' },
        { item: 'Nuts and seeds (macadamia, pecans, walnuts)', icon: '🥜' },
        { item: 'Heavy cream', icon: '🥛' },
      ],
      eatOccasionally: [
        { item: 'Berries (small portions — blueberries, raspberries)', icon: '🫐' },
        { item: 'Dark chocolate (85%+ cocoa)', icon: '🍫' },
        { item: 'Full-fat yogurt (plain, unsweetened)', icon: '🥛' },
        { item: 'Onions and garlic (in small amounts)', icon: '🧅' },
        { item: 'Tomatoes (small portions)', icon: '🍅' },
      ],
      minimize: [
        { item: 'Bread, pasta, rice, and grains', icon: '🍞' },
        { item: 'Sugar and sweets', icon: '🍬' },
        { item: 'Potatoes and starchy vegetables', icon: '🥔' },
        { item: 'Fruit juice and soda', icon: '🥤' },
        { item: 'Beans and legumes', icon: '🫘' },
        { item: 'Low-fat and diet products', icon: '⚠️' },
        { item: 'Seed oils (canola, soybean, sunflower)', icon: '🚫' },
      ],
    },
    electrolytes: {
      why: 'When you reduce carbs significantly, your body excretes more water and electrolytes. During tapering, electrolyte balance is especially important because deficiencies can mimic or worsen withdrawal symptoms like anxiety, muscle cramps, and brain fog.',
      minerals: [
        { name: 'Sodium', amount: '3,000–5,000 mg/day', sources: 'Salt your food generously, bone broth, pickles, salted nuts' },
        { name: 'Potassium', amount: '3,000–4,000 mg/day', sources: 'Avocados, spinach, salmon, mushrooms, salt substitute (lite salt)' },
        { name: 'Magnesium', amount: '300–500 mg/day', sources: 'Dark chocolate, spinach, pumpkin seeds, or a magnesium glycinate supplement' },
      ],
    },
    budgetTips: [
      'Buy eggs in bulk — they are the most affordable keto staple and extremely nutrient-dense.',
      'Chicken thighs are much cheaper than breasts and have more fat, making them ideal for keto.',
      'Frozen vegetables (broccoli, spinach, cauliflower) are just as nutritious and often half the price.',
      'Buy butter and cheese when on sale and freeze them — both freeze well for months.',
      'Canned sardines and mackerel are affordable omega-3 rich proteins.',
      'Cook with lard or tallow instead of expensive specialty oils.',
    ],
    lowEffortMeals: [
      { name: 'Scrambled eggs with butter and cheese', description: 'Crack 3 eggs into a pan with butter. Scramble. Top with shredded cheese. Done in 5 minutes.' },
      { name: 'Canned sardines on a bed of spinach', description: 'Open a can of sardines, put them on a plate of raw spinach. Drizzle olive oil and salt. No cooking needed.' },
      { name: 'Rotisserie chicken with avocado', description: 'Buy a pre-made rotisserie chicken. Pull off some meat, eat with half an avocado. Zero effort.' },
      { name: 'Cheese and salami roll-ups', description: 'Roll slices of salami around cheese sticks. Eat with a handful of olives. No cooking.' },
      { name: 'Buttered broccoli with ground beef', description: 'Brown ground beef in a pan. Steam broccoli in the microwave. Add butter and salt.' },
    ],
  },
  {
    name: 'Low-Carb',
    slug: 'low-carb',
    description: 'Reduce sugar and processed carbs. The most practical starting point for people actively tapering.',
    evidence: 'Moderate',
    taperingFit: 'High',
    badgeColor: 'teal',
    details: {
      what: 'A low-carb diet reduces daily carbohydrate intake to roughly 50-100g per day — significantly less than the standard Western diet (250-350g) but more flexible than strict keto. The focus is on eliminating sugar, refined grains, and processed foods while eating whole foods, protein, healthy fats, and non-starchy vegetables.',
      mechanism: 'Reducing carbohydrates stabilizes blood sugar levels, which reduces the "spike and crash" pattern that can trigger anxiety, irritability, and cravings. Lower carb intake also reduces insulin levels, which may decrease inflammation and improve the brain\'s ability to use fat for fuel. While not producing the deep ketosis of a ketogenic diet, low-carb eating still shifts metabolism toward more stable energy production.',
      tapering: 'Low-carb is often the most practical starting point for people tapering medications. The blood sugar stabilization alone can make a meaningful difference in mood stability and energy levels. Members frequently report that cutting sugar and processed carbs reduces the severity of mood swings during dose reductions. It is also easier to maintain socially than strict keto.',
      considerations: 'This approach is more sustainable for most people long-term. It allows for berries, some legumes, and small amounts of whole grains. There is no strict adaptation period like keto, though the first week without sugar can involve cravings. A good "entry level" diet for someone new to dietary changes.',
    },
    foods: {
      eatFreely: [
        { item: 'All meats and poultry', icon: '🍗' },
        { item: 'Fish and seafood', icon: '🐟' },
        { item: 'Eggs', icon: '🥚' },
        { item: 'Non-starchy vegetables (leafy greens, peppers, tomatoes)', icon: '🥬' },
        { item: 'Olive oil, butter, coconut oil', icon: '🫒' },
        { item: 'Cheese and full-fat dairy', icon: '🧀' },
        { item: 'Nuts and seeds', icon: '🥜' },
        { item: 'Avocados', icon: '🥑' },
        { item: 'Berries (strawberries, blueberries, raspberries)', icon: '🍓' },
      ],
      eatOccasionally: [
        { item: 'Sweet potatoes (small portions)', icon: '🍠' },
        { item: 'Legumes (lentils, chickpeas)', icon: '🫘' },
        { item: 'Whole fruit (apples, oranges — one serving)', icon: '🍎' },
        { item: 'Quinoa and oats (small portions)', icon: '🌾' },
        { item: 'Dark chocolate (70%+)', icon: '🍫' },
        { item: 'Wine (occasional, one glass)', icon: '🍷' },
      ],
      minimize: [
        { item: 'White bread, pasta, and white rice', icon: '🍞' },
        { item: 'Sugar, candy, and baked goods', icon: '🍰' },
        { item: 'Soda, juice, and sweetened drinks', icon: '🥤' },
        { item: 'Processed snack foods (chips, crackers)', icon: '🍿' },
        { item: 'Breakfast cereals', icon: '🥣' },
        { item: 'Seed oils (canola, soybean)', icon: '🚫' },
      ],
    },
    electrolytes: {
      why: 'Even moderate carb reduction can increase water loss in the first few weeks. Staying on top of electrolytes helps prevent headaches, fatigue, and irritability — symptoms that can overlap with tapering withdrawal.',
      minerals: [
        { name: 'Sodium', amount: '2,000–4,000 mg/day', sources: 'Salt your food, bone broth, olives, pickles' },
        { name: 'Potassium', amount: '3,000–4,000 mg/day', sources: 'Avocados, spinach, bananas (in moderation), sweet potatoes' },
        { name: 'Magnesium', amount: '300–400 mg/day', sources: 'Pumpkin seeds, dark chocolate, spinach, almonds' },
      ],
    },
    budgetTips: [
      'Buy whole chickens and use the bones for broth — much cheaper per pound than individual cuts.',
      'Frozen berries are cheaper than fresh and perfect for smoothies or topping yogurt.',
      'Canned tuna and salmon are affordable protein sources that keep for months.',
      'Buy vegetables in season for the best prices and peak nutrition.',
      'Batch cook ground beef or chicken thighs at the start of the week.',
      'Plain full-fat yogurt is cheaper than flavored varieties and has no added sugar.',
    ],
    lowEffortMeals: [
      { name: 'Greek yogurt with berries and nuts', description: 'Scoop plain full-fat yogurt into a bowl. Add a handful of berries and some walnuts. No cooking.' },
      { name: 'Tuna salad lettuce wraps', description: 'Mix a can of tuna with mayo and mustard. Wrap in large lettuce leaves.' },
      { name: 'Chicken and vegetable stir-fry', description: 'Sauté leftover chicken with frozen stir-fry vegetables in olive oil. Season with soy sauce or salt.' },
      { name: 'Cheese omelette', description: 'Whisk 3 eggs, pour into a buttered pan, add cheese. Fold when set. 5 minutes total.' },
      { name: 'Deli meat and cheese plate', description: 'Arrange deli turkey, cheese slices, olives, and cucumber on a plate. No cooking required.' },
    ],
  },
  {
    name: 'Anti-Inflammatory',
    slug: 'anti-inflammatory',
    description: 'Omega-3 rich, whole foods. Targets the neuroinflammation that worsens withdrawal symptoms.',
    evidence: 'Moderate',
    taperingFit: 'Medium',
    badgeColor: 'amber',
    details: {
      what: 'The anti-inflammatory diet emphasizes foods that reduce chronic inflammation: fatty fish rich in omega-3s, colorful vegetables, berries, olive oil, nuts, seeds, and anti-inflammatory spices like turmeric and ginger. It minimizes seed oils, refined sugar, processed foods, and refined grains — the primary dietary drivers of inflammation.',
      mechanism: 'Chronic low-grade inflammation has been linked to depression, anxiety, bipolar disorder, and other psychiatric conditions. Inflammatory cytokines can cross the blood-brain barrier, impairing neurotransmitter production, reducing neuroplasticity, and damaging mitochondria. By reducing dietary sources of inflammation and increasing anti-inflammatory nutrients (especially omega-3 fatty acids), this diet aims to calm the immune system and support brain function.',
      tapering: 'During medication withdrawal, the nervous system is already under significant stress. Reducing inflammatory load through diet may help the brain heal more efficiently. Some members report less nerve pain, fewer muscle aches, and better sleep quality on an anti-inflammatory diet. The omega-3 focus is particularly relevant — there is evidence that omega-3 supplementation may support mood stability during psychiatric medication changes.',
      considerations: 'This is the least restrictive of the four approaches and closest to a "normal" diet. It allows whole grains, legumes, and most fruits. It is a good option for people who find keto or low-carb too restrictive, or who have digestive issues that make high-fat diets uncomfortable. Can be combined with a low-carb approach for additional benefit.',
    },
    foods: {
      eatFreely: [
        { item: 'Fatty fish (salmon, sardines, mackerel, herring)', icon: '🐟' },
        { item: 'Leafy greens (spinach, kale, arugula)', icon: '🥬' },
        { item: 'Colorful vegetables (bell peppers, beets, sweet potatoes)', icon: '🫑' },
        { item: 'Berries (blueberries, strawberries, cherries)', icon: '🫐' },
        { item: 'Extra virgin olive oil', icon: '🫒' },
        { item: 'Nuts (walnuts, almonds, cashews)', icon: '🥜' },
        { item: 'Seeds (flax, chia, hemp)', icon: '🌱' },
        { item: 'Turmeric, ginger, garlic, and anti-inflammatory spices', icon: '🧄' },
        { item: 'Bone broth', icon: '🍲' },
        { item: 'Green tea', icon: '🍵' },
      ],
      eatOccasionally: [
        { item: 'Whole grains (brown rice, quinoa, oats)', icon: '🌾' },
        { item: 'Legumes (lentils, black beans)', icon: '🫘' },
        { item: 'Eggs (pasture-raised preferred)', icon: '🥚' },
        { item: 'Poultry (chicken, turkey)', icon: '🍗' },
        { item: 'Dark chocolate (70%+)', icon: '🍫' },
        { item: 'Red wine (occasional)', icon: '🍷' },
      ],
      minimize: [
        { item: 'Seed oils (canola, soybean, sunflower, corn oil)', icon: '🚫' },
        { item: 'Refined sugar and high-fructose corn syrup', icon: '🍬' },
        { item: 'Processed meats (hot dogs, deli meats with nitrates)', icon: '🌭' },
        { item: 'Refined grains (white bread, white pasta)', icon: '🍞' },
        { item: 'Fried foods', icon: '🍟' },
        { item: 'Artificial sweeteners and additives', icon: '⚠️' },
        { item: 'Excessive alcohol', icon: '🍺' },
      ],
    },
    electrolytes: {
      why: 'An anti-inflammatory diet is generally less restrictive with carbs, so electrolyte loss is less dramatic than keto. However, during tapering, your nervous system is under extra stress, and adequate magnesium and potassium support nerve function and sleep quality.',
      minerals: [
        { name: 'Sodium', amount: '2,000–3,000 mg/day', sources: 'Salt your food with sea salt or Himalayan salt, olives, bone broth' },
        { name: 'Potassium', amount: '3,500–4,500 mg/day', sources: 'Sweet potatoes, bananas, spinach, avocados, coconut water' },
        { name: 'Magnesium', amount: '300–400 mg/day', sources: 'Pumpkin seeds, spinach, dark chocolate, almonds, epsom salt baths' },
      ],
    },
    budgetTips: [
      'Canned wild salmon and sardines are affordable and loaded with omega-3s.',
      'Buy frozen berries and spinach — same nutrition as fresh at half the cost.',
      'Turmeric, ginger, and garlic are cheap pantry staples with powerful anti-inflammatory effects.',
      'Dried lentils and beans are some of the cheapest foods available and cook easily.',
      'Buy olive oil in bulk from warehouse stores for significant savings.',
      'Grow herbs like basil, rosemary, and parsley on a windowsill — nearly free once established.',
    ],
    lowEffortMeals: [
      { name: 'Salmon with steamed broccoli', description: 'Bake a salmon fillet at 400°F for 12 minutes. Microwave frozen broccoli. Drizzle both with olive oil.' },
      { name: 'Berry smoothie with spinach', description: 'Blend frozen berries, a handful of spinach, and some flax seeds with water or almond milk.' },
      { name: 'Sardine and avocado toast', description: 'Mash avocado on whole grain toast, top with canned sardines and a squeeze of lemon.' },
      { name: 'Quick turmeric chicken soup', description: 'Simmer canned chicken broth with shredded rotisserie chicken, turmeric, ginger, and spinach.' },
      { name: 'Nut and berry trail mix plate', description: 'Handful of walnuts, almonds, dark chocolate chips, and dried cherries. No prep at all.' },
    ],
  },
  {
    name: 'Carnivore',
    slug: 'carnivore',
    description: 'Meat-based elimination diet. Used by some members with severe food sensitivities during withdrawal.',
    evidence: 'Emerging',
    taperingFit: 'Medium',
    badgeColor: 'gray',
    details: {
      what: 'The carnivore diet is an elimination diet consisting primarily of animal foods: meat, fish, eggs, and sometimes dairy. All plant foods are removed. It is the most restrictive of the four approaches but also the simplest — there are very few decisions to make about what to eat.',
      mechanism: 'The carnivore diet works as an elimination protocol, removing all potential plant-based irritants (lectins, oxalates, phytates, FODMAPs) that can cause inflammation and digestive issues in sensitive individuals. It is inherently very low carb (zero carb in strict form), so it produces ketosis. Meat is also extremely nutrient-dense, providing bioavailable B vitamins, iron, zinc, and complete proteins needed for neurotransmitter production.',
      tapering: 'Some community members with autoimmune conditions, severe gut issues, or food sensitivities report that the carnivore approach has been the most effective for them during tapering. The simplicity is also valued by those with very low energy — there is nothing to plan, measure, or think about. However, the evidence base is primarily anecdotal and from self-reported surveys rather than clinical trials.',
      considerations: 'This is the most extreme dietary approach and not suitable for everyone. It can be socially difficult to maintain. Some people experience digestive changes in the first few weeks. Long-term safety data is limited. Most practitioners recommend trying low-carb or keto first and only considering carnivore if those approaches do not adequately address symptoms.',
    },
    foods: {
      eatFreely: [
        { item: 'Beef (steaks, ground beef, roasts)', icon: '🥩' },
        { item: 'Lamb and goat', icon: '🍖' },
        { item: 'Pork (chops, bacon, pork belly)', icon: '🥓' },
        { item: 'Poultry (chicken, turkey, duck)', icon: '🍗' },
        { item: 'Fish and shellfish (all types)', icon: '🐟' },
        { item: 'Eggs', icon: '🥚' },
        { item: 'Bone broth and bone marrow', icon: '🍲' },
        { item: 'Organ meats (liver, heart — highly nutritious)', icon: '🫀' },
        { item: 'Animal fats (tallow, lard, duck fat)', icon: '🧈' },
      ],
      eatOccasionally: [
        { item: 'Butter and ghee', icon: '🧈' },
        { item: 'Hard cheeses (if tolerated)', icon: '🧀' },
        { item: 'Heavy cream (if tolerated)', icon: '🥛' },
        { item: 'Salt and basic seasonings', icon: '🧂' },
        { item: 'Coffee and tea (some include, some exclude)', icon: '☕' },
      ],
      minimize: [
        { item: 'All plant foods (strict version)', icon: '🥬' },
        { item: 'Sugar and sweeteners', icon: '🍬' },
        { item: 'Grains and bread', icon: '🍞' },
        { item: 'Processed meats with fillers or additives', icon: '🌭' },
        { item: 'Seed oils', icon: '🚫' },
        { item: 'Alcohol', icon: '🍺' },
      ],
    },
    electrolytes: {
      why: 'The carnivore diet is very low carb, so the same electrolyte considerations as keto apply. Meat is rich in many minerals, but you may still need to add salt liberally. During tapering, adequate sodium and magnesium are critical for nervous system stability.',
      minerals: [
        { name: 'Sodium', amount: '4,000–6,000 mg/day', sources: 'Salt your meat generously, drink bone broth daily, add salt to water' },
        { name: 'Potassium', amount: '2,000–3,500 mg/day', sources: 'Meat is naturally rich in potassium — beef, salmon, and pork are good sources' },
        { name: 'Magnesium', amount: '300–500 mg/day', sources: 'Bone broth, fish, organ meats, or a magnesium glycinate supplement if needed' },
      ],
    },
    budgetTips: [
      'Ground beef is the most affordable carnivore staple — buy in bulk and freeze.',
      'Eggs are incredibly cheap and one of the most nutrient-dense foods available.',
      'Buy whole chickens instead of parts — roast the chicken, then make broth from the bones.',
      'Look for marked-down meat at the end of the day at grocery stores.',
      'Organ meats (liver, heart) are often the cheapest cuts and the most nutritious.',
      'Canned fish (sardines, mackerel) are an affordable way to add variety.',
    ],
    lowEffortMeals: [
      { name: 'Pan-seared burger patties', description: 'Shape ground beef into patties, season with salt, cook in a pan 4 minutes per side. Simple and filling.' },
      { name: 'Bacon and eggs', description: 'Cook bacon in a pan, fry eggs in the bacon fat. Classic, easy, and deeply satisfying.' },
      { name: 'Rotisserie chicken', description: 'Buy a pre-made rotisserie chicken from the store. Pull meat off and eat. Literally zero effort.' },
      { name: 'Canned sardines with bone broth', description: 'Open a can of sardines. Heat a mug of bone broth. A complete meal with minimal effort.' },
      { name: 'Steak with butter', description: 'Season a steak with salt, sear in a hot pan 3-4 minutes per side, top with butter. Restaurant quality at home.' },
    ],
  },
];

export function getDietBySlug(slug) {
  return DIETS.find((d) => d.slug === slug) || null;
}

export const DIET_SLUGS = DIETS.map((d) => d.slug);
