export const VIDEOS = [
  // ── Beginner ──
  {
    id: 'georgia-ede-descent',
    videoId: 'TXlVfwJ6RQU',
    title: 'Our Descent into Madness: Modern Diets & the Mental Health Crisis',
    speaker: 'Georgia Ede, MD',
    credential: 'Psychiatrist, Nutritional Psychiatry Expert',
    summary: 'Dr. Ede makes the evidence-based case that modern diets — not lifestyle alone — are driving the global mental health crisis, covering RCTs of dietary intervention, insulin resistance, inflammation, and what dietary patterns offer the most hope.',
    level: 'Beginner',
    duration: '33 min',
  },
  {
    id: 'metabolic-mind-intro',
    videoId: '4PHzq0BXWNY',
    title: 'What Is Metabolic Psychiatry?',
    speaker: 'Metabolic Mind',
    credential: 'Educational Nonprofit — Baszucki Group',
    summary: 'A concise overview of metabolic psychiatry — what it is, the evidence behind it, and why it matters for mental health treatment.',
    level: 'Beginner',
    duration: '8 min',
  },
  {
    id: 'ede-phc2023',
    videoId: '23_fnung5To',
    title: 'What Is Nutritional & Metabolic Psychiatry?',
    speaker: 'Georgia Ede, MD',
    credential: 'Psychiatrist, Author of Change Your Diet, Change Your Mind',
    summary: 'Dr. Ede\'s comprehensive Public Health Collaboration 2023 talk defining the field of nutritional and metabolic psychiatry — how food affects brain chemistry, what the clinical evidence shows, and how diet interacts with psychiatric medication.',
    level: 'Beginner',
    duration: '59 min',
  },
  {
    id: 'horowitz-tapering-metabolic-mind',
    videoId: 'Ks70lCqRC9k',
    title: 'Safe Tapering Practices for Antidepressants',
    speaker: 'Mark Horowitz, MD PhD',
    credential: 'Lead Author, Maudsley Deprescribing Guidelines',
    summary: 'The world\'s leading expert on psychiatric medication tapering explains hyperbolic tapering, how to distinguish withdrawal from relapse, the role of metabolic support during deprescribing, and his personal experience coming off antidepressants.',
    level: 'Beginner',
    duration: '47 min',
  },

  // ── Intermediate ──
  {
    id: 'palmer-huberman',
    videoId: 'xjEFo3a1AnI',
    title: 'Diet & Nutrition for Mental Health',
    speaker: 'Chris Palmer, MD',
    credential: 'Harvard Psychiatrist, Author of Brain Energy',
    summary: 'Dr. Palmer discusses his brain energy theory with Andrew Huberman, covering how mitochondrial dysfunction may drive psychiatric conditions and how diet can help. The most comprehensive single overview of Palmer\'s work.',
    level: 'Intermediate',
    duration: '3 hr 4 min',
  },
  {
    id: 'palmer-brain-energy-metabolic-mind',
    videoId: 'oC-sQogfh3Q',
    title: 'Brain Energy, Mitochondria, and Mental Health',
    speaker: 'Chris Palmer, MD',
    credential: 'Harvard Psychiatrist, Author of Brain Energy',
    summary: 'Tighter and more focused than the Huberman episode — Palmer explains the brain energy theory, the role of mitochondria in mental illness, how ketogenic therapy and lifestyle changes improve mitochondrial health, and the impact of psychiatric medications on metabolism.',
    level: 'Intermediate',
    duration: '48 min',
  },
  {
    id: 'bret-scher-metabolic',
    videoId: 'n9IxomBusuw',
    title: 'Metabolic Health & Mental Illness',
    speaker: 'Bret Scher, MD',
    credential: 'Cardiologist, Metabolic Mind Medical Director',
    summary: 'Dr. Scher interviews leading researchers about the connection between metabolic health, ketogenic diets, and psychiatric conditions.',
    level: 'Intermediate',
    duration: '45 min',
  },
  {
    id: 'ede-change-your-diet',
    videoId: 'ws_AlyJNo2I',
    title: 'Change Your Diet, Change Your Mind — with Dr. Georgia Ede',
    speaker: 'Georgia Ede, MD',
    credential: 'Psychiatrist, Author of Change Your Diet, Change Your Mind',
    summary: 'Georgia Ede on Metabolic Mind — practical and focused on which foods affect which brain conditions, what a brain-healthy diet actually needs to do, and how insulin resistance connects to psychiatric symptoms.',
    level: 'Intermediate',
    duration: '39 min',
  },
  {
    id: 'sethi-metabolic-psychiatry',
    videoId: 'mVPhltup0IY',
    title: 'How to Use Metabolic Psychiatry to Heal Anxiety & Depression',
    speaker: 'Shebani Sethi, MD',
    credential: 'Stanford Psychiatrist, Founder of Metabolic Psychiatry Clinic',
    summary: 'Dr. Shebani Sethi — who coined the term "metabolic psychiatry" and founded the first academic metabolic psychiatry clinic — explains how insulin resistance and metabolic dysfunction drive psychiatric symptoms and what the clinical evidence from Stanford\'s programme shows.',
    level: 'Intermediate',
    duration: '1 hr 9 min',
  },
  {
    id: 'horowitz-withdrawal-truth',
    videoId: 'Z0uPRdfCpeU',
    title: 'The Truth About Antidepressant Withdrawal Symptoms',
    speaker: 'Mark Horowitz, MD PhD',
    credential: 'Lead Author, Maudsley Deprescribing Guidelines',
    summary: 'Dr. Horowitz addresses a contested JAMA study on antidepressant withdrawal — explaining why withdrawal is systematically underdiagnosed, how to distinguish it from relapse, and what the best evidence actually shows for coming off psychiatric medications safely.',
    level: 'Intermediate',
    duration: '37 min',
  },

  // ── Deep Dive ──
  {
    id: 'palmer-huberman-2025',
    videoId: 'hCyvqRq5YmM',
    title: 'Transform Your Mental Health with Diet & Lifestyle',
    speaker: 'Chris Palmer, MD',
    credential: 'Harvard Psychiatrist, Author of Brain Energy',
    summary: 'Palmer\'s 2025 return to the Huberman Lab — an updated and expanded view of the brain energy theory, mitochondrial health, the 6 pillars of lifestyle medicine for psychiatric recovery, ketogenic therapy evidence, supplements, and the impact of ultra-processed food on psychiatric outcomes.',
    level: 'Deep Dive',
    duration: '3 hr 13 min',
  },
  {
    id: 'palmer-mclean-lecture',
    videoId: '8ubhikXxj4E',
    title: 'The Ketogenic Diet in Medicine and Psychiatry',
    speaker: 'Chris Palmer, MD',
    credential: 'Harvard Psychiatrist, McLean Hospital',
    summary: 'A formal clinical lecture covering the ketogenic diet\'s mechanism in epilepsy, PURE study results, and clinical case evidence for ketogenic therapy in schizophrenia and bipolar disorder. The most evidence-heavy presentation of the clinical science.',
    level: 'Deep Dive',
    duration: '1 hr 3 min',
  },
  {
    id: 'ede-clinical-cases',
    videoId: 'RGv2AuIGRSg',
    title: 'Treating Serious Mental Illness with Ketogenic Therapy — Clinical Cases',
    speaker: 'Georgia Ede, MD',
    credential: 'Psychiatrist, Nutritional Psychiatry Expert',
    summary: 'Georgia Ede presents five real patient cases of serious mental illness — schizophrenia, bipolar disorder, and severe depression — treated with ketogenic therapy, including detailed outcomes and medication changes. Recorded at the first Metabolic Psychiatry Roadmap Retreat.',
    level: 'Deep Dive',
    duration: '15 min',
  },
  {
    id: 'horowitz-therapeutics-initiative',
    videoId: 'LRr09mvMEAU',
    title: 'Antidepressant Withdrawal Effects & How to Safely Stop Them',
    speaker: 'Mark Horowitz, MD PhD',
    credential: 'Lead Author, Maudsley Deprescribing Guidelines',
    summary: 'A CME-grade clinical lecture for prescribers — covers the neuroscience of antidepressant withdrawal, receptor occupancy curves, the mathematics of hyperbolic tapering, and practical prescribing guidance for supporting patients through deprescribing.',
    level: 'Deep Dive',
    duration: '52 min',
  },
];

export const VIDEO_LEVELS = ['Beginner', 'Intermediate', 'Deep Dive'];

export function getVideosByLevel(level) {
  return VIDEOS.filter((v) => v.level === level);
}
